// English texts for the interface (see i18n.js): the admin screen, the shared side menu, the shared dialogs and toasts,
// and the Hebrew texts the server sends (health checks, automatic-choice reasons, default model names)
window.EN = Object.assign(window.EN || {}, {
  "בחירת תאריך": "Pick a date",
  "ניקוי": "Clear",
  "בחירת שנה": "Pick a year",
  "החודש הקודם": "Previous month",
  "החודש הבא": "Next month",
  "שנים קודמות": "Earlier years",
  "שנים הבאות": "Later years",
  "לטיפול": "To handle",
  "שלום, מנהל": "Hello, admin",
  "הנה מה שקורה בשער היום": "Here's what's happening in the gateway today",
  "שאלו את הבינה המלאכותית… (נפתח במסך הצ'אט)": "Ask the AI… (opens in the chat screen)",
  "שאלה לבינה המלאכותית, נפתחת במסך הצ'אט": "Question for the AI, opens in the chat screen",
  "פתיחה במסך הצ'אט": "Open in the chat screen",
  // side menu, shared by every page
  "ניווט": "Navigation",
  "ראשי": "Main",
  "לוח בקרה": "Dashboard",
  "ניהול": "Manage",
  "משתמשים ומפתחות": "Users and keys",
  "מודלים": "Models",
  "צוותים": "Teams",
  "מקורות מידע": "Knowledge sources",
  "בקרה": "Monitor",
  "דוחות": "Reports",
  "אבטחה": "Security",
  "לוג טוקנים": "Token log",
  "יומן שינויים": "Change log",
  "עובדים": "Employees",
  "מסך הצ'אט": "Chat",
  "תיעוד": "Docs",
  "הצגה או הסתרה של התפריט": "Show or hide the menu",
  "סגירת התפריט": "Close the menu",
  "מיקום": "Breadcrumb",
  "רענון": "Refresh",
  "מ": "A",
  "מנהל": "Admin",
  // shared dialogs and toasts (ui.js)
  "סגירת ההודעה": "Dismiss",
  "אישור": "OK",
  "ביטול": "Cancel",
  "סגירה": "Close",
  "שמירה": "Save",

  // page title, footer, login
  "FireGate · ניהול": "FireGate · Admin",
  "FireGate · ניהול שימוש בבינה מלאכותית": "FireGate · AI usage management",
  "מסך הצ'אט לעובדים": "Employee chat",
  "כניסה מבחוץ": "Sign in from outside",
  "מתוך רשת המשרד אין צורך בסיסמה. מבחוץ צריך את סיסמת המנהל.": "Inside the office network no password is needed. From outside, enter the admin password.",
  "סיסמת מנהל": "Admin password",
  "כניסה": "Sign in",
  "סיסמה שגויה": "Wrong password",

  // dashboard
  "משתמש חדש": "New user",
  "צעדים ראשונים": "Getting started",
  "דורש טיפול": "Needs attention",
  "הוצאה יומית": "Daily spend",
  "30 הימים האחרונים": "Last 30 days",
  "הוצאה לפי מודל": "Spend by model",
  "החודש": "This month",
  "המשתמשים שהוציאו הכי הרבה": "Top spenders",
  "שם": "Name",
  "צוות": "Team",
  "בקשות": "Requests",
  "הוצאה": "Spend",
  "מצב תקציב": "Budget status",
  "צוותים מול תקציב": "Teams vs. budget",
  "הוצאה מצטברת החודש": "Cumulative spend this month",
  "מול החודש הקודם ומול תקציבי הצוותים": "Against last month and the team budgets",
  "צפי ניצול התקציב": "Projected budget use",
  "כמה משתמשים יסיימו את החודש בכל טווח": "How many users will end the month in each range",
  "מתי שואלים": "When people ask",
  "בקשות לפי יום ושעה, 4 השבועות האחרונים": "Requests by day and hour, last 4 weeks",
  "הוצאה חודשית לפי צוות": "Monthly spend by team",
  "ארבעת החודשים האחרונים": "Last four months",
  "הוצאה החודש": "Spent this month",
  "השבוע לעומת השבוע הקודם": "This week vs. last week",
  "צפי לסוף החודש": "Projected for the month",
  "בקשות החודש": "Requests this month",
  "משתמשים פעילים": "Active users",
  "חדש": "New",
  "לחבר ספק: להכניס מפתח של Anthropic, ‏OpenAI או Google לקובץ .env ולהפעיל את השער מחדש": "Connect a provider: put an Anthropic, OpenAI or Google key in the .env file and restart the gateway",
  "ליצור צוות עם תקציב חודשי": "Create a team with a monthly budget",
  "ליצור משתמש ראשון": "Create the first user",
  "לשאול שאלה ראשונה במסך הצ'אט": "Ask a first question in the chat",
  "לעשות את זה": "Do it",
  "לפרטים": "Details",
  "הכל תקין: אין חריגות תקציב ואין הערות אבטחה פתוחות.": "All good: no budget overruns and no open security notes.",
  "חסום": "Blocked",
  "אין שימוש החודש": "No usage this month",
  "אין צוותים עדיין": "No teams yet",
  "לנסות שוב": "Try again",
  "עוד אין שימוש ב-30 הימים האחרונים": "No usage in the last 30 days yet",
  "הוצאה יומית ב-30 הימים האחרונים": "Daily spend over the last 30 days",
  "תקציבי הצוותים": "Team budgets",
  "עד 50%": "Under 50%",
  "מעל 150%": "Over 150%",
  "ראשון": "Sun", "שני": "Mon", "שלישי": "Tue", "רביעי": "Wed", "חמישי": "Thu", "שישי": "Fri", "שבת": "Sat",
  "מפת חום של בקשות לפי יום בשבוע ושעה": "Heat map of requests by weekday and hour",
  "מעט": "Less",
  "הרבה": "More",
  "אחר": "Other",
  "אין שימוש עדיין": "No usage yet",
  "חלוקת ההוצאה לפי מודל": "Spend split by model",
  "סה\"כ החודש": "Total this month",
  "סה\"כ": "Total",

  // users and keys
  "חיפוש לפי שם או צוות": "Search by name or team",
  "חיפוש משתמשים": "Search users",
  "\"צפי\" הוא כמה המשתמש יוציא עד סוף החודש בקצב הנוכחי. \"מומלץ\" הוא הגבוה מבין הצפי לבין החודש הקודם, ועוד 20% מרווח.": "\"Projected\" is what the user will spend by the end of the month at the current pace. \"Suggested\" is the higher of the projection and last month, plus a 20% margin.",
  "צפי": "Projected",
  "תקציב מומלץ": "Suggested budget",
  "גישה": "Access",
  "פעולות": "Actions",
  "ללא תקרה": "No cap",
  "מתאים": "Fits",
  "להחיל": "Apply",
  "להעלות את התקציב לסכום המומלץ לפני שהחשבון ייחסם": "Raise the budget to the suggested amount before the account gets blocked",
  "עדכון התקציב": "Update budget",
  "ביטול השינוי": "Undo",
  "יעבור את התקציב": "Will exceed budget",
  "צ'אט": "Chat",
  "נעול": "Locked",
  "עריכה": "Edit",
  "מחיקה": "Delete",
  "הכניסה לצ'אט והמפתח יפסיקו לעבוד מיד. היסטוריית השאלות נשארת ביומן.": "Chat sign-in and the key stop working right away. The question history stays in the log.",
  "אין משתמשים שמתאימים לחיפוש.": "No users match the search.",
  "אין משתמשים עדיין. לחצו על \"משתמש חדש\".": "No users yet. Click \"New user\".",
  "חכם": "smart",
  "מהיר": "fast",
  "כבוי": "Off",

  // user dialog
  "מי": "Who",
  "שם (עובד, אפליקציה או לקוח)": "Name (employee, app or customer)",
  "מגבלות": "Limits",
  "תקציב חודשי ($)": "Monthly budget ($)",
  "בקשות לדקה (0 = ללא הגבלה)": "Requests per minute (0 = no limit)",
  "מודלים מותרים": "Allowed models",
  "מחיר לכל מיליון טוקנים: נכנס / יוצא": "Price per million tokens: in / out",
  "ליצור מפתח לאפליקציות (API)": "Create an API key for apps",
  "בלי צוות": "No team",
  "סיסמה חדשה לצ'אט (ריק = בלי שינוי; גם משחרר נעילה)": "New chat password (empty = no change; also unlocks the account)",
  "סיסמה לכניסה לצ'אט (לפחות 8 תווים; ריק = בלי צ'אט)": "Chat sign-in password (at least 8 characters; empty = no chat)",
  "מפתח לאפליקציות (API)": "API key for apps",
  "אין מפתח": "No key",
  "מפתח חדש": "New key",
  "יצירת מפתח": "Create key",
  "ביטול מפתח": "Revoke key",
  "מפתח חדש?": "New key?",
  "יצירת מפתח?": "Create key?",
  "ביטול מפתח?": "Revoke key?",
  "המפתח החדש": "The new key",
  "העתקה": "Copy",
  "הועתק ✓": "Copied ✓",

  // teams
  "צוות חדש": "New team",
  "כשתקציב הצוות נגמר, כל חברי הצוות נחסמים, גם אם נשאר להם תקציב אישי. תקציב צוות 0 = בלי תקרה לצוות.": "When the team budget runs out, every team member is blocked, even if they have personal budget left. Team budget 0 = no team cap.",
  "חברים": "Members",
  "סכום תקציבי החברים": "Sum of member budgets",
  "החברים יישארו בלי צוות, והתקציב של הצוות יימחק. ההיסטוריה ביומן נשארת.": "Members will be left without a team and the team budget is deleted. The log history stays.",
  "מחיקת הצוות": "Delete team",
  "אין צוותים עדיין. לחצו על \"צוות חדש\".": "No teams yet. Click \"New team\".",
  "שם הצוות": "Team name",
  "תקציב חודשי לצוות ($, 0 = ללא תקרה)": "Monthly team budget ($, 0 = no cap)",
  "הצוות נוצר.": "Team created.",

  // models
  "מודל חדש": "New model",
  "כל מודל שעובדים ואפליקציות יכולים להשתמש בו. מודל כבוי נחסם אצל כולם מיד, גם אם הותר להם. המחיר קובע איך מחושבת העלות של כל שאלה, אז כדאי לעדכן אותו כשהספק משנה מחיר.": "Every model employees and apps can use. A model that is off is blocked for everyone right away, even if they were allowed it. The price sets how each question's cost is calculated, so update it when the provider changes prices.",
  "בחירה אוטומטית של מודל": "Automatic model choice",
  "כשעובד בוחר \"אוטומטי\" בצ'אט, השער שולח שאלות קצרות ופשוטות למודל הזול, וקוד, ניתוח, השוואה, טקסט ארוך או שיחה ארוכה למודל החזק. הסיבה לבחירה מוצגת לעובד ונרשמת ביומן.": "When an employee picks \"Automatic\" in the chat, the gateway sends short, simple questions to the cheap model, and code, analysis, comparisons, long text or long conversations to the strong model. The reason for the choice is shown to the employee and logged.",
  "בחירה אוטומטית פעילה": "Automatic choice on",
  "פעיל": "On",
  "מודל זול": "Cheap model",
  "מודל חזק": "Strong model",
  "הוצאה יומית לפי מודל": "Daily spend by model",
  "בקשות מול הוצאה": "Requests vs. spend",
  "כמה מהבקשות עוברות בכל מודל, וכמה מהכסף. פער גדול = מודל יקר לבקשה.": "Each model's share of requests and of money. A big gap = a model that is expensive per request.",
  "חלק מהבקשות": "Share of requests",
  "חלק מההוצאה (בצבע המודל)": "Share of spend (in the model's color)",
  "חלק מההוצאה": "Share of spend",
  "מודל": "Model",
  "ספק": "Provider",
  "מחיר למיליון טוקנים": "Price per million tokens",
  "שימוש החודש": "Usage this month",
  "משתמשים": "Users",
  "ברירת מחדל": "Default",
  "כיבוי": "Turn off",
  "אף משתמש לא מורשה להשתמש בו כרגע.": "No user is allowed to use it right now.",
  "הגדרות הבחירה האוטומטית נשמרו.": "Automatic choice settings saved.",
  "חלקים חוזרים בשיחות נקראו מהמטמון של הספק במחיר מוזל": "Repeated parts of conversations were read from the provider's cache at a discount",
  "מפתחות ספקים:": "Provider keys:",
  "יש מפתח בקובץ .env": "Key found in the .env file",
  "אין מפתח בקובץ .env: המודלים של הספק הזה לא יעבדו": "No key in the .env file: this provider's models won't work",
  "הכינוי · השם אצל הספק": "Alias · provider's model ID",
  "אין מפתח לספק הזה": "No key for this provider",
  "לקבוע": "Set",
  "המודל שנבחר אוטומטית בצ'אט ומסומן למשתמש חדש": "The model picked by default in the chat and checked for new users",
  "בדיקה": "Test",
  "שולח שאלה קצרה לספק ובודק שהמפתח והשם עובדים": "Sends a short question to the provider to check that the key and model ID work",
  "המודל יימחק מהרשימה. השאלות שנשאלו בו נשארות ביומן.": "The model is removed from the list. Questions asked with it stay in the log.",
  "אין מודלים. לחצו על \"מודל חדש\".": "No models. Click \"New model\".",
  "בלי גיבוי": "No backup",

  // model dialog
  "זיהוי": "Identity",
  "כינוי (מה שאפליקציות שולחות בשדה model)": "Alias (what apps send in the model field)",
  "שם לתצוגה (מה שעובדים רואים בצ'אט)": "Display name (what employees see in the chat)",
  "אצל הספק": "At the provider",
  "שם המודל אצל הספק": "Provider's model ID",
  "מחיר לטוקנים נכנסים ($ למיליון)": "Input token price ($ per million)",
  "מחיר לטוקנים יוצאים ($ למיליון)": "Output token price ($ per million)",
  "מחיר לטוקנים שנקראים מהמטמון של הספק ($ למיליון; ריק = עשירית ממחיר הנכנסים)": "Price for tokens read from the provider's cache ($ per million; empty = a tenth of the input price)",
  "את השם המדויק והמחירים מעתיקים מעמוד המחירים של הספק.": "Copy the exact model ID and prices from the provider's pricing page.",
  "כשהספק לא זמין": "When the provider is down",
  "מודל גיבוי": "Backup model",
  "אם הספק עמוס או לא עונה, השאלה עוברת אוטומטית למודל הגיבוי ומחויבת לפי המחיר שלו. באפליקציות זה עובד רק בין מודלים באותו פורמט: Claude עם Claude, או GPT עם Gemini.": "If the provider is overloaded or not answering, the question moves automatically to the backup model and is billed at its price. For apps this only works between models with the same format: Claude with Claude, or GPT with Gemini.",
  "פעיל: אפשר להשתמש בו": "On: available for use",

  // error messages (admin.js turns the server's English errors into Hebrew first)
  "הכינוי צריך להיות 2 עד 40 אותיות אנגליות קטנות, ספרות, נקודה, מקף או קו תחתון": "The alias must be 2 to 40 lowercase English letters, digits, dot, dash or underscore",
  "ספק לא מוכר": "Unknown provider",
  "צריך למלא את שם המודל אצל הספק": "Fill in the provider's model ID",
  "המחיר לא יכול להיות שלילי": "The price can't be negative",
  "זה מודל ברירת המחדל. קודם קובעים ברירת מחדל אחרת, ואז אפשר לכבות אותו": "This is the default model. Set another default first, then you can turn it off",
  "זה מודל ברירת המחדל. קודם קובעים ברירת מחדל אחרת": "This is the default model. Set another default first",
  "מודל הגיבוי צריך להיות מודל אחר מהרשימה": "The backup model must be another model from the list",
  "חיפוש לפי משמעות צריך מפתח של OpenAI או Google בקובץ .env": "Meaning search needs an OpenAI or Google key in the .env file",
  "קריאת PDF צריכה את הספרייה pypdf בשרת": "Reading PDF needs the pypdf package on the server",
  "כתובת שרת ה-MCP צריכה להתחיל ב-http:// או https://": "The MCP server address must start with http:// or https://",
  "צריך לבדוק חיבור ולבחור את כלי החיפוש": "Test the connection and choose the search tool",
  "אפשר לסנכרן רק תיקייה או שרת MCP במצב סנכרון": "Only folders and MCP servers in sync mode can be synced",
  "קודם מדליקים את המודל, ואז אפשר לקבוע אותו כברירת מחדל": "Turn the model on first, then you can make it the default",
  "אין מה לעדכן": "Nothing to update",
  "צריך לבחור לפחות מודל אחד": "Pick at least one model",
  "הסיסמה צריכה להיות באורך 8 תווים לפחות": "The password must be at least 8 characters",
  "התקציב לא יכול להיות שלילי": "The budget can't be negative",
  "צריך למלא שם": "Fill in a name",
  "צריך סיסמה לצ'אט, מפתח API, או את שניהם": "Give a chat password, an API key, or both",
  "השם הזה כבר קיים": "That name already exists",
  "התיקייה לא נמצאה בשרת": "The folder was not found on the server",

  // knowledge sources
  "מקור חדש": "New source",
  "מסמכים של החברה שהצ'אט מחפש בהם ומצטט מהם. כל עובד רואה רק מקורות שהצוות שלו קיבל גישה אליהם. אפשר להעלות PDF, ‏Word וקבצי טקסט (Markdown, CSV, HTML ועוד), או לחבר תיקייה בשרת שמסתנכרנת בלחיצה.": "Company documents the chat searches and quotes. Each employee only sees sources their team has access to. You can upload PDF, Word and text files (Markdown, CSV, HTML and more), or connect a server folder that syncs with one click.",
  "חיפוש לפי משמעות: כבוי": "Meaning search: off",
  "צריך מפתח של OpenAI או Google בקובץ ‎.env. בינתיים החיפוש לפי מילים בלבד.": "Needs an OpenAI or Google key in the .env file. Until then search is by words only.",
  "קריאת PDF לא זמינה בשרת הזה (חסרה הספרייה pypdf).": "PDF reading isn't available on this server (the pypdf package is missing).",
  "האינדקס עודכן.": "Index updated.",
  "כל העובדים": "All employees",
  "אף אחד עוד לא קיבל גישה": "No one has access yet",
  "הסרה": "Remove",
  "המסמך לא יופיע יותר בחיפוש בצ'אט.": "The document will no longer show up in chat search.",
  "תיקייה בשרת": "Server folder",
  "קבצים שהועלו": "Uploaded files",
  "שרת MCP": "MCP server",
  "סנכרון מסמכים": "Document sync",
  "חיפוש חי": "Live search",
  "גישה:": "Access:",
  "בדיקת חיבור": "Test connection",
  "העלאת קבצים": "Upload files",
  "סנכרון עכשיו": "Sync now",
  "כל המסמכים שבו יימחקו מהשער ולא יופיעו בצ'אט. קבצים בתיקייה בשרת עצמו לא נמחקים.": "All its documents are deleted from the gateway and won't appear in the chat. Files in the server folder itself are not deleted.",
  "מחיקת המקור": "Delete source",
  "סנכרון אחרון:": "Last sync:",
  "עוד לא סונכרן": "Not synced yet",
  "רשימת המסמכים": "Document list",
  "המקור הזה לא שומר מסמכים: בכל שאלה השער שואל את השרת בזמן אמת, ומסנן את התשובה.": "This source stores no documents: on each question the gateway asks the server live and filters the answer.",
  "לחצו על \"סנכרון עכשיו\" כדי לקרוא את המסמכים": "Click \"Sync now\" to read the documents",
  "עוד אין מסמכים. לחצו על \"העלאת קבצים\".": "No documents yet. Click \"Upload files\".",
  "אין מקורות מידע עדיין. לחצו על \"מקור חדש\".": "No knowledge sources yet. Click \"New source\".",
  "נמצא תוכן חשוד בקובץ": "Suspicious content found in the file",
  "להעלות בכל זאת": "Upload anyway",
  "מקור מידע חדש": "New knowledge source",
  "שמור. ריק = בלי שינוי": "Saved. Empty = no change",
  "המקור נוצר.": "Source created.",
  // source dialog
  "שם המקור": "Source name",
  "תיאור קצר (העובדים רואים אותו)": "Short description (employees see it)",
  "סוג": "Type",
  "קבצים שמעלים כאן": "Files uploaded here",
  "נתיב התיקייה בשרת": "Folder path on the server",
  "חיבור לשרת MCP": "MCP server connection",
  "MCP הוא דרך סטנדרטית שבה מערכות (CRM, ויקי, מערכת כרטיסים) חושפות מידע לבינה מלאכותית. מכניסים את הכתובת שהמערכת נותנת.": "MCP is a standard way for systems (CRM, wiki, ticketing) to share data with AI. Enter the address the system gives you.",
  "כתובת השרת": "Server address",
  "מפתח גישה (אם השרת דורש)": "Access token (if the server needs one)",
  "איך להשתמש בו": "How to use it",
  "חיפוש חי: בכל שאלה, לשאול את השרת": "Live search: ask the server on every question",
  "סנכרון: להעתיק את המסמכים שלו לאינדקס": "Sync: copy its documents into the index",
  "כלי החיפוש": "Search tool",
  "השדה שמקבל את השאלה": "Field that takes the question",
  "מי רשאי לחפש במקור הזה": "Who may search this source",

  // reports
  "חודש": "Month",
  "הורדה לאקסל": "Download for Excel",
  "לפי צוות": "By team",
  "תקציב": "Budget",
  "ניצול": "Used",
  "לפי משתמש": "By user",
  "טוקנים": "Tokens",
  "לפי מודל": "By model",
  "מתוכם מהמטמון": "From cache",
  "כל הספקים": "All providers",
  "אנשים ואפליקציות": "People and apps",
  "שהשתמשו בחודש הזה": "Who used it this month",
  "ממוצע לבקשה": "Average per request",
  "עלות ממוצעת": "Average cost",
  "אין שימוש בחודש הזה": "No usage this month",
  // report file (CSV)
  "דוח שימוש בבינה מלאכותית": "AI usage report",
  "הוצאה ($)": "Spend ($)",
  "תקציב ($)": "Budget ($)",
  "טוקנים נכנסים": "Input tokens",
  "טוקנים יוצאים": "Output tokens",
  "טוקנים מהמטמון": "Cached tokens",

  // security
  "סינון לפי סוג אירוע": "Filter by event type",
  "כל האירועים": "All events",
  "בדיקת מצב": "Health check",
  "אירועי אבטחה": "Security events",
  "200 האחרונים": "Last 200",
  "שאלות חשודות נרשמות ולא נחסמות, כי עובדים שואלים בצדק על קוד ופקודות. מסמכים חשודים נחסמים בהעלאה, כי הם מגיעים לכל מי שמחפש בהם. תשובה עם פקודה מסוכנת מקבלת אזהרה לעובד.": "Suspicious questions are logged, not blocked, because employees rightly ask about code and commands. Suspicious documents are blocked on upload, because they reach everyone who searches them. An answer with a dangerous command comes with a warning to the employee.",
  "מתי": "When",
  "אירוע": "Event",
  "פרטים": "Details",
  "שאלה חשודה": "Suspicious question",
  "תשובה עם פקודה מסוכנת": "Answer with a dangerous command",
  "מידע רגיש הוסתר": "Sensitive data masked",
  "בקשה מאתר זר נחסמה": "Cross-site request blocked",
  "כתובת לא מוכרת נחסמה": "Unknown host blocked",
  "חשבון ננעל": "Account locked",
  "סיסמת מנהל שגויה מבחוץ": "Wrong admin password from outside",
  "מסמך חשוד לא נקלט": "Suspicious document refused",
  "מסמך חשוד הועלה באישור": "Suspicious document uploaded with approval",
  "ניסיון לעקוף הוראות": "Attempt to override instructions",
  "קוד דפדפן": "Browser code",
  "פקודה מסוכנת": "Dangerous command",
  "שאלות חשודות": "Suspicious questions",
  "נרשמו ביומן": "Logged",
  "מידע רגיש שהוסתר": "Sensitive data masked",
  "לפני שיצא לספק": "Before it reached the provider",
  "בקשות שנחסמו": "Blocked requests",
  "מאתרים זרים או מבחוץ": "From other sites or outside",
  "תשובות עם פקודה מסוכנת": "Answers with a dangerous command",
  "העובד קיבל אזהרה": "Employee was warned",
  "7 ימים אחרונים": "last 7 days",
  "אין אירועים": "No events",
  "מה קורה לשאלה שמנסה לעקוף את ההוראות של המודל נקבע במדיניות למעלה. שאלות על קוד ופקודות רק נרשמות, כי עובדים שואלים עליהן בצדק. מסמכים חשודים נחסמים בהעלאה, כי הם מגיעים לכל מי שמחפש בהם. תשובה עם פקודה מסוכנת או קישור חשוד מקבלת אזהרה לעובד.":
    "What happens to a question that tries to get around the model's instructions is set in the policy above. Questions about code and commands are only logged, because employees rightly ask about them. Suspicious documents are blocked on upload, because they reach everyone who searches them. An answer with a dangerous command or a suspicious link comes with a warning to the employee.",
  "מדיניות": "Policy",
  "ניסיון לעקוף את ההוראות של המודל": "Attempt to get around the model's instructions",
  "לחסום את השאלה": "Block the question",
  "לשלוח ולרשום ביומן": "Send it and log it",
  "מידע רגיש (תעודת זהות, כרטיס אשראי, טלפון, אימייל, מפתחות)": "Sensitive data (ID numbers, credit cards, phone numbers, emails, keys)",
  "להסתיר את המידע ולשלוח": "Hide the data and send",
  "לשלוח בלי להסתיר ולרשום ביומן": "Send without hiding and log it",
  "שמירת המדיניות": "Save policy",
  "המדיניות נשמרה.": "Policy saved.",
  "יומן השינויים לא שונה": "Change log is intact",
  "מישהו שינה או מחק שורות ביומן השינויים מחוץ למערכת.": "Someone changed or deleted rows in the change log outside the system.",
  "שורות נמחקו מסוף יומן השינויים מחוץ למערכת.": "Rows were deleted from the end of the change log outside the system.",
  "200 האחרונות": "Last 200",
  "סיבה": "Reason",
  "קטע מהשאלה": "Question excerpt",
  "לא נחסמו בקשות": "No blocked requests",
  "שאלה עם מידע רגיש נחסמה": "Question with sensitive data blocked",
  "מידע רגיש נשלח בלי הסתרה": "Sensitive data sent unhidden",
  "מסמך חשוד נשלח למודל": "Suspicious document sent to the model",
  "מפתח גישה הוסתר מתשובה": "Access key hidden from an answer",
  "קישור חשוד בתשובה": "Suspicious link in an answer",
  "התשובה חשפה את ההוראות של השער": "Answer revealed the gateway's instructions",
  "כלי MCP שמשנה מידע לא הופעל": "MCP tool that changes data was not run",
  "הוצאה חריגה": "Unusual spending",
  "יותר מדי סיסמאות שגויות מאותה כתובת": "Too many wrong passwords from one address",
  "ניסיון לשחרר את המודל מהכללים": "Attempt to free the model from its rules",
  "הכלי יכול לשנות מידע": "the tool can change data",
  "השרת לא מציע את הכלי": "the server doesn't offer this tool",
  "הכלי לא מקבל את הפרמטר": "the tool doesn't take this argument",
  "נחסמה": "blocked",
  "התקציב האישי נגמר": "Personal budget used up",
  "תקציב הצוות נגמר": "Team budget used up",
  "יותר מדי בקשות בדקה": "Too many requests per minute",
  "נגמרו הטוקנים להיום": "Daily tokens used up",
  "יותר מדי שאלות במקביל": "Too many questions at once",
  "מידע רגיש": "Sensitive data",
  "מודל לא מורשה": "Model not allowed",
  "המודל כבוי": "Model is off",
  "מפתח שפג תוקפו": "Expired key",
  "יותר מדי הודעות בבקשה אחת": "Too many messages in one request",
  "השאלות והתשובות שמורות מוצפנות, והמפתח מוגדר בהגדרות השרת": "Questions and answers are stored encrypted, and the key is set in the server settings",
  "השאלות והתשובות שמורות מוצפנות, אבל מפתח ההצפנה נמצא בקובץ ליד מסד הנתונים. כדאי לשמור עותק שלו במקום אחר: בלי המפתח אי אפשר לקרוא את השאלות, התשובות והשיחות.":
    "Questions and answers are stored encrypted, but the encryption key is in a file next to the database. Keep a copy somewhere else: without the key the questions, answers and chats can't be read.",
  // health checks sent by the server
  "חיבור מוצפן (HTTPS) עם דומיין": "Encrypted connection (HTTPS) with a domain",
  "אין דומיין, ולכן החיבור לא מוצפן. השאלות והסיסמאות עוברות ברשת כטקסט גלוי. מתאים לרשת המשרד בלבד.": "No domain, so the connection isn't encrypted. Questions and passwords cross the network as plain text. Fine for the office network only.",
  "מסך הניהול סגור מבחוץ": "The admin screen is closed to outside access",
  "סיסמת המנהל לגישה מבחוץ חזקה": "The admin password for outside access is strong",
  "סיסמת המנהל לגישה מבחוץ קצרה מ-16 תווים": "The admin password for outside access is shorter than 16 characters",
  "לכל מפתחות ה-API יש הגבלת קצב": "Every API key has a rate limit",
  "מפתח API אחד בלי הגבלת קצב. מפתח שדלף יכול לרוקן תקציב מהר.": "One API key has no rate limit. A leaked key can drain a budget fast.",
  "כניסה לצ'אט עם סיסמה": "Chat sign-in needs a password",
  "הצ'אט פתוח בלי סיסמה ברשת המשרד (OPEN_ACCESS): כל אחד יכול לבחור כל שם, להשתמש בתקציב שלו ולראות את השיחות שלו.": "The chat is open without a password on the office network (OPEN_ACCESS): anyone can pick any name, use that person's budget and see their conversations.",
  "אין מפתחות ספקים בקובץ .env": "No provider keys in the .env file",

  // question log
  "סינון לפי שם, צוות או מודל": "Filter by name, team or model",
  "טוקנים נכנסו": "Tokens in",
  "טוקנים יצאו": "Tokens out",
  "עלות": "Cost",
  "מוצגות 200 השאלות האחרונות. כל השאלות נשמרות במסד הנתונים.": "Showing the last 200 questions. All questions are kept in the database.",
  "שאלה ותשובה": "Question and answer",
  "אין שאלות": "No questions",
  "(בדיקת מודל)": "(model test)",
  "(אינדקס מסמכים)": "(document index)",

  // change log
  "פעולה": "Action",
  "אין שינויים עדיין": "No changes yet",
  "חשבון נוצר": "Account created",
  "חשבון עודכן": "Account updated",
  "חשבון נמחק": "Account deleted",
  "הונפק מפתח חדש": "New key issued",
  "מפתח בוטל": "Key revoked",
  "צוות נשמר": "Team saved",
  "צוות נמחק": "Team deleted",
  "מקור מידע נשמר": "Knowledge source saved",
  "מקור מידע נמחק": "Knowledge source deleted",
  "הועלו מסמכים": "Documents uploaded",
  "תיקייה סונכרנה": "Folder synced",
  "מודל נשמר": "Model saved",
  "מודל נמחק": "Model deleted",
  "נקבע מודל ברירת מחדל": "Default model set",
  "בחירה אוטומטית עודכנה": "Automatic choice updated",
  "מדיניות האבטחה עודכנה": "Security policy updated",
  "המפתח בלי תאריך תפוגה": "key without an expiry date",
  "טוקנים ליום (0 = ללא הגבלה)": "Tokens per day (0 = no limit)",
  "המפתח בתוקף עד (ריק = בלי תאריך תפוגה)": "Key valid until (empty = no expiry date)",
  "הבקשה גדולה מדי. אפשר להעלות פחות קבצים בכל פעם.": "The request is too large. Upload fewer files at a time.",
  "מספר הטוקנים ליום לא יכול להיות שלילי": "Tokens per day can't be negative",
  "תאריך התפוגה של המפתח לא תקין": "The key's expiry date isn't valid",
  "צריך נתיב מלא לתיקייה בשרת (למשל /data/docs)": "Give the folder's full path on the server (for example /data/docs)",
  "התיקייה מחוץ לתיקיות שמותר לקרוא מהן (ההגדרה SOURCE_ROOTS בשרת)": "The folder is outside the folders the server may read (the SOURCE_ROOTS setting)",
  "שם הכלי או הפרמטר של שרת ה-MCP לא תקין": "The MCP tool or argument name isn't valid",
  "מדיניות לא מוכרת": "Unknown policy",
  "סיסמה הוחלפה": "Password changed",
  "הודלק": "turned on",
  "כובה": "turned off",
  "נוסף": "added",

  // automatic-choice reasons the server sends (shown next to the answer in the chat)
  "שאלה ארוכה": "long question",
  "קוד, ניתוח או השוואה": "code, analysis or comparison",
  "שיחה ארוכה": "long conversation",
  "שאלה קצרה ופשוטה": "short, simple question",

  // archive (nothing is deleted)
  "ארכיון": "Archive",
  "העברה לארכיון": "Move to archive",
  "שחזור": "Restore",
  "הועבר לארכיון": "Archived",
  "שוחזר מהארכיון": "Restored from archive",
  "משתמש": "User",
  "מקור מידע": "Knowledge source",
  "מסמך": "Document",
  "שיחה": "Chat",
  "הארכיון ריק.": "The archive is empty.",
  "שום מידע לא נמחק. משתמש, צוות, מודל, מקור מידע או מסמך שהועברו לארכיון לא מופיעים במסכים ולא עובדים, אבל נשמרים עם כל ההיסטוריה שלהם, ואפשר לשחזר אותם. ההוצאה שלהם נשארת ביומן ובדוחות.":
    "Nothing is ever deleted. A user, team, model, knowledge source or document moved to the archive disappears from the screens and stops working, but is kept with all its history and can be restored. Its spending stays in the log and in the reports.",
  "הצוות ייעלם מהרשימות ומהבחירה של משתמשים. קודם צריך להעביר את האנשים שבו לצוות אחר. ההיסטוריה ביומן נשארת. אפשר לשחזר מהארכיון.":
    "The team disappears from the lists and from the choices for users. Move its people to another team first. The log history stays. It can be restored from the archive.",
  "הכניסה לצ'אט והמפתח יפסיקו לעבוד מיד. היסטוריית השאלות וההוצאה נשארת ביומן ובדוחות. אפשר לשחזר מהארכיון.":
    "Chat sign-in and the key stop working right away. The question and spending history stays in the log and the reports. It can be restored from the archive.",
  "המסמך לא יופיע יותר בחיפוש בצ'אט. אפשר לשחזר מהארכיון.": "The document will no longer show up in chat search. It can be restored from the archive.",
  "המקור והמסמכים שבו לא יופיעו בצ'אט ובחיפוש. קבצים בתיקייה בשרת עצמו לא משתנים. אפשר לשחזר מהארכיון.":
    "The source and its documents won't appear in the chat or in search. Files in the server folder itself are not changed. It can be restored from the archive.",
  "המודל ייעלם מהרשימה ואי אפשר יהיה להשתמש בו. השאלות שנשאלו בו נשארות ביומן. אפשר לשחזר מהארכיון.":
    "The model disappears from the list and can't be used. Questions asked with it stay in the log. It can be restored from the archive.",
  "השם הזה שייך לפריט שנמצא בארכיון. אפשר לשחזר אותו מעמוד הארכיון.": "That name belongs to an item in the archive. Restore it from the Archive page.",
  "הצוות של המשתמש נמצא בארכיון. קודם משחזרים את הצוות, ואז את המשתמש.": "The user's team is in the archive. Restore the team first, then the user.",
  "יש עדיין אנשים בצוות. קודם מעבירים אותם לצוות אחר, ואז אפשר להעביר את הצוות לארכיון.": "The team still has people. Move them to another team first, then the team can be archived.",
  // one person's page
  "הפעילות של המשתמש": "The user's activity",
  "פעילות אחרונה": "Recent activity",
  "היסטוריית שינויים": "Change history",
  "שיחות": "Chats",
  "בארכיון": "Archived",
  "המשתמש לא נמצא.": "User not found.",
  "חזרה למשתמשים": "Back to users",
  "טוקנים החודש": "Tokens this month",
  "שאלה": "Question",
  "תשובה": "Answer",
  "אין בקשות עדיין": "No requests yet",
  "אין שיחות שמורות": "No saved chats",
  "המשתמש בארכיון: הכניסה לצ'אט והמפתח לא עובדים. כל ההיסטוריה נשמרת, ואפשר לשחזר אותו מעמוד הארכיון.":
    "This user is archived: chat sign-in and the key don't work. All the history is kept, and the user can be restored from the Archive page.",

  // savings recommendations
  "המלצות לחיסכון": "Savings recommendations",
  "לכל ההמלצות": "See all recommendations",
  "השימוש נראה יעיל: אין כרגע המלצות לחיסכון.": "Usage looks efficient: no savings recommendations right now.",
  "להפעיל בחירה אוטומטית": "Turn on automatic choice",
  "להגדרות הבחירה האוטומטית": "Automatic choice settings",
  "לכבות את המודל": "Turn the model off",

  // teams: chargeback codes and the team's model policy
  "חיוב פנימי": "Chargeback",
  "מרכז עלות": "Cost center",
  "חשבון": "GL account",
  "חשבון בהנהלת החשבונות": "GL account (bookkeeping)",
  "מודלים מותרים לצוות": "Models the team may use",
  "בלי סימון, הצוות לא מגביל. עם סימון, חברי הצוות יכולים להשתמש רק במודלים המסומנים, גם אם הותרו להם אישית מודלים נוספים. זה חל גם על הבחירה האוטומטית ועל מודל הגיבוי.":
    "Nothing checked: the team sets no limit. With models checked, team members can use only those, even if more models were allowed to them personally. This also applies to automatic choice and to the backup model.",
  "מודל אחד מותר": "1 model allowed",
  "חסום ע\"י מדיניות הצוות": "Blocked by team policy",
  "הצוות לא מגביל מודלים": "the team sets no model limit",
  "בלי מרכז עלות": "no cost center",
  "בלי חשבון": "no GL account",
  "מודל שהצוות לא מורשה בו": "Model not allowed for the team",
  "צריך לבחור מודלים מהרשימה": "Pick models from the list",

  // chargeback export
  "חיוב פנימי לפי צוות": "Chargeback by team",
  "הורדה ל-CSV": "Download CSV",
  "הורדה ל-JSON": "Download JSON",
  "העלות של כל צוות בחודש שנבחר למעלה, עם מרכז העלות והחשבון בהנהלת החשבונות שלו (קובעים אותם בעריכת הצוות). בקובץ, שמות העמודות באנגלית, כדי שמערכת הנהלת החשבונות תקלוט אותם כמו שהם.":
    "Each team's cost in the month chosen above, with its cost center and GL account (set them when editing the team). In the file the column names are in English, so the accounting system can import them as they are.",
  "ללא צוות": "No team",

  // monthly summary by email
  "סיכום חודשי במייל": "Monthly summary by email",
  "ב-1 לכל חודש, אחרי 08:00, השער שולח להנהלה סיכום של החודש שעבר: הוצאה מול החודש הקודם, הצוותים והמשתמשים שהוציאו הכי הרבה, הוצאה לפי מודל, המלצות לחיסכון, אירועי אבטחה וחריגות מהתקציב. תצוגה מקדימה ו\"לשלוח עכשיו\" הן לחודש שנבחר למעלה.":
    "On the 1st of every month, after 08:00, the gateway emails management a summary of the month before: spend against the previous month, the teams and users who spent the most, spend by model, savings recommendations, security events and budget overruns. Preview and \"Send now\" use the month chosen above.",
  "נמענים (כתובות מייל, מופרדות בפסיק)": "Recipients (email addresses, separated by commas)",
  "שליחה אוטומטית פעילה": "automatic sending on",
  "שליחה אוטומטית כבויה": "automatic sending off",
  "שליחה אוטומטית ב-1 לכל חודש": "Send automatically on the 1st of every month",
  "תצוגה מקדימה": "Preview",
  "לשלוח עכשיו": "Send now",
  "תצוגה מקדימה של המייל": "Email preview",
  "שרת הדואר מוגדר": "Mail server set up",
  "שרת הדואר לא מוגדר": "No mail server",
  "צריך למלא SMTP_HOST ו-SMTP_FROM בהגדרות השרת": "Set SMTP_HOST and SMTP_FROM in the server settings",
  "עוד לא נשלח סיכום.": "No summary sent yet.",
  "הגדרות הסיכום החודשי נשמרו.": "Monthly summary settings saved.",
  "לשלוח את הסיכום עכשיו?": "Send the summary now?",
  "שליחה": "Send",
  "אין עדיין נמענים שמורים.": "There are no saved recipients yet.",
  "הגדרות הסיכום החודשי עודכנו": "Monthly summary settings changed",
  "הסיכום החודשי נשלח": "Monthly summary sent",
  "נשלח אוטומטית": "sent automatically",
  "נשלח ידנית": "sent by hand",
  "בלי נמענים": "no recipients",
  "שליחת הסיכום החודשי נכשלה": "Monthly summary failed to send",
  "שרת הדואר לא מוגדר. צריך למלא SMTP_HOST ו-SMTP_FROM בהגדרות השרת ולהפעיל אותו מחדש.":
    "No mail server is set up. Set SMTP_HOST and SMTP_FROM in the server settings and restart it.",
  "אין נמענים שמורים. צריך להוסיף לפחות כתובת מייל אחת ולשמור.": "No saved recipients. Add at least one email address and save.",
  "אפשר עד 50 נמענים": "Up to 50 recipients",
  "החודש לא תקין": "Invalid month",

  // models on the company's own server, and speed
  "שרת מודלים מקומי": "Local model server",
  "מודלים שרצים על שרת של החברה עם Ollama או vLLM. השאלות לא יוצאות מהרשת של החברה, ואין תשלום לפי טוקנים (אפשר לקבוע מחיר פנימי בעריכת המודל). כותבים את כתובת השרת, בודקים חיבור, ומוסיפים את המודלים שהוא מציע. מפתח גישה לשרת, אם צריך, נכנס רק להגדרות השרת (LOCAL_API_KEY).":
    "Models running on a company server with Ollama or vLLM. Questions never leave the company network, and there is no per-token charge (you can set an internal price when editing the model). Type the server's address, check the connection, and add the models it offers. An access key for the server, if it needs one, goes only into the server settings (LOCAL_API_KEY).",
  "כתובת השרת": "Server address",
  "בדיקת חיבור": "Check connection",
  "כתובת שמורה": "Address saved",
  "לא מוגדר": "Not set up",
  "כבר ברשימת המודלים": "Already in the model list",
  "הוספת מודל": "Add model",
  "כתובת השרת נשמרה.": "Server address saved.",
  "השרת עונה, אבל אין בו עדיין מודלים.": "The server answers, but it has no models yet.",
  "שרת החברה": "Company server",
  "שרת החברה \u200f(Ollama / vLLM)": "Company server (Ollama / vLLM)",
  "מקומי": "local",
  "נשמרה כתובת לשרת": "A server address is saved",
  "אין כתובת לשרת: המודלים המקומיים לא יעבדו": "No server address: the local models won't work",
  "אין כתובת לשרת המקומי": "No address for the local server",
  "כתובת שרת המודלים המקומי עודכנה": "Local model server address updated",
  "כתובת השרת צריכה להיראות כך: http://server:11434/v1": "The server address should look like http://server:11434/v1",
  "עוד לא נשמרה כתובת לשרת המודלים המקומי": "No address has been saved for the local model server yet",
  "לשלוח למודל המקומי": "Send to the local model",
  "מידע רגיש נענה במודל המקומי": "Sensitive data answered by the local model",
  "\"לשלוח למודל המקומי\": שאלה עם מידע רגיש נענית בלי הסתרה במודל שרץ על שרת החברה, אם העובד מורשה להשתמש בו. אחרת המידע מוסתר.":
    "\"Send to the local model\": a question with sensitive data is answered, unmasked, by a model on the company's server, if the employee may use it. Otherwise the data is masked.",
  "אין מודל מקומי פעיל, ולכן המידע מוסתר בינתיים.": "No local model is on, so the data is masked for now.",
  "\"לשלוח למודל המקומי\" נפתח אחרי שמוסיפים מודל משרת החברה בעמוד המודלים.":
    "\"Send to the local model\" opens up once a model from the company's server is added on the Models page.",
  "להעדיף את המודל המהיר מבין המתאימים": "Prefer the fastest suitable model",
  "בין המודלים שמתאימים לשאלה ובמחיר דומה (עד פי 2 לכאן או לכאן), אצל כל ספק שמותר לעובד: זה שענה הכי מהר ב-24 השעות האחרונות. נחשבים רק מודלים עם 20 תשובות לפחות.":
    "Among the models that suit the question and cost about the same (up to 2x either way), at any provider the employee may use: the one that answered fastest in the last 24 hours. Only models with at least 20 answers count.",
  "מהירות תגובה": "Response speed",
  "תקופה": "Period",
  "24 השעות האחרונות": "Last 24 hours",
  "7 הימים האחרונים": "Last 7 days",
  "כמה זמן לוקח לכל מודל לענות. \"חציון\" הוא הזמן שחצי מהתשובות מהירות ממנו, \"95%\" הוא הזמן ש-95 מכל 100 תשובות מהירות ממנו (המקרים האיטיים). \"זמן עד מילה ראשונה\" הוא כמה זמן העובד מחכה עד שהתשובה מתחילה להופיע.":
    "How long each model takes to answer. \"Median\" is the time half the answers beat, \"95%\" the time 95 of every 100 answers beat (the slow cases). \"Time to first word\" is how long the employee waits until the answer starts to appear.",
  "מהירות תגובה לפי מודל": "Response speed by model",
  "חציון": "Median",
  "זמן עד מילה ראשונה": "Time to first word",
  "שגיאות": "Errors",
  "חציון לפי ספק, בכל שעה ב-48 השעות האחרונות": "Median by provider, each hour of the last 48",
  "איטי מהרגיל עכשיו": "Slower than usual now",
  "עוד אין נתוני מהירות": "No speed data yet",
  "עוד אין נתוני מהירות ב-48 השעות האחרונות": "No speed data in the last 48 hours yet",
  "חציון זמן התשובה לפי ספק בכל שעה ב-48 השעות האחרונות. המספרים המלאים בטבלה שלצד הגרף.":
    "Median answer time by provider for each of the last 48 hours. The full numbers are in the table next to the chart.",
  "מערכת": "System",
  "הגדרות": "Settings",
  "חיפוש הגדרה, למשל תקציב או מייל": "Search settings, e.g. budget or email",
  "חיפוש בכל ההגדרות": "Search all settings",
  "פרקי ההגדרות": "Settings sections",
  "פרק": "Section",
  "יש שינויים שלא נשמרו": "You have unsaved changes",
  "שינויים שלא נשמרו": "Unsaved changes",
  "הגדרות מיוחדות": "Special settings",
  "ברירת המחדל היא \"כמו ההגדרה הכללית\". הגדרה מיוחדת חלה רק על חברי הצוות.": "The default is \"like the global setting\". A special setting applies only to the team's members.",
  "מודלים שרצים על שרת של החברה עם Ollama או vLLM. השאלות לא יוצאות מהרשת של החברה, ואין תשלום לפי טוקנים (אפשר לקבוע מחיר פנימי בעריכת המודל). את כתובת השרת והמפתח קובעים בהגדרות; כאן בודקים חיבור ומוסיפים את המודלים שהוא מציע.": "Models running on a company server with Ollama or vLLM. Questions don't leave the company network, and there's no per-token charge (you can set an internal price when editing the model). The server's address and key are set in Settings; here you test the connection and add the models it offers.",
  "פעם בחודש השער שולח להנהלה סיכום של החודש שעבר: הוצאה מול החודש הקודם, הצוותים והמשתמשים שהוציאו הכי הרבה, הוצאה לפי מודל, המלצות לחיסכון, אירועי אבטחה וחריגות מהתקציב. תצוגה מקדימה ו\"לשלוח עכשיו\" הן לחודש שנבחר למעלה.": "Once a month the gateway sends management a summary of the month before: spending against the previous month, the teams and users who spent the most, spending by model, savings recommendations, security events and budget overruns. \"Preview\" and \"Send now\" are for the month chosen above.",
  "פעילה": "On",
  "כבויה": "Off",
  "מודל זול:": "Cheap model:",
  "מודל חזק:": "Strong model:",
  "מעדיפה את המודל המהיר": "Prefers the fast model",
  "שינוי בהגדרות": "Change in settings",
  "שליחה אוטומטית כבויה": "Automatic sending off",
  "שליחה אוטומטית פעילה": "Automatic sending on",
  "אין נמענים": "No recipients",
  "כתובת השרת:": "Server address:",
  "לא נקבעה": "Not set",
  "עקיפת הוראות:": "Getting around instructions:",
  "מידע רגיש:": "Sensitive data:",
  "צוות אחד עם חריג": "One team with its own value",
  "בקרוב": "Coming soon",
  "מקובץ ההגדרות בשרת": "From the server's settings file",
  "שונה מברירת המחדל": "Changed from the default",
  "חזרה לברירת מחדל": "Back to the default",
  "אחרי הפעלה מחדש": "After a restart",
  "חל מיד": "Applies at once",
  "הגדרות ששונו מברירת המחדל": "Settings changed from the default",
  "אין הגדרה שמתאימה לחיפוש.": "No setting matches the search.",
  "ההגדרות בפרק הזה יגיעו בשלב הבא של השער. בינתיים הן מוצגות כבויות.": "The settings in this section come with the gateway's next phase. Until then they are shown turned off.",
  "גיבוי עכשיו": "Back up now",
  "עוד אין גיבויים": "No backups yet",
  "מחיקה": "Deletion",
  "קבוע": "Fixed",
  "שום מידע לא נמחק, רק עובר לארכיון.": "No data is ever deleted, only moved to the archive.",
  "מצב ההצפנה": "Encryption",
  "השאלות, התשובות, השיחות והסודות שמורים מוצפנים.": "Questions, answers, chats and secrets are stored encrypted.",
  "מפתח ההצפנה": "Encryption key",
  "בהגדרות השרת (FIREGATE_DATA_KEY)": "In the server settings (FIREGATE_DATA_KEY)",
  "תזכורת": "Reminder",
  "כדאי לשמור עותק של קובץ המפתח במקום אחר: בלעדיו אי אפשר לקרוא את המידע המוצפן.": "Keep a copy of the key file somewhere else: without it the encrypted data can't be read.",
  "מחיקה והצפנה": "Deletion and encryption",
  "מצב המערכת": "System status",
  "גרסה": "Version",
  "מסד הנתונים": "Database",
  "גודל המסד": "Database size",
  "פורט": "Port",
  "הצפנה": "Encryption",
  "מוצפן": "Encrypted",
  "המפתח בהגדרות השרת": "the key is in the server settings",
  "המפתח בקובץ ליד המסד": "the key is in a file next to the database",
  "גיבויים": "Backups",
  "אזור זמן": "Time zone",
  "אין בשרת נתוני אזורי זמן, ולכן נעשה שימוש בשעון של השרת.": "This server has no time zone data, so the server's clock is used.",
  "פורט ומיקום המסד נקבעים בהגדרות השרת (PORT, GATEWAY_DB).": "The port and the database location are set in the server settings (PORT, GATEWAY_DB).",
  "בדיקת מצב": "Health check",
  "פעולות": "Actions",
  "ייצוא הגדרות": "Export settings",
  "ייבוא הגדרות": "Import settings",
  "בדיקת עדכונים": "Check for updates",
  "ייצוא: קובץ בלי סודות, להעברה בין שרתים או לפני שינוי גדול. בדיקת עדכונים פונה ל-GitHub רק כשלוחצים.": "Export: a file without secrets, to move between servers or before a big change. The update check contacts GitHub only when clicked.",
  "אין חיבור ל-GitHub כרגע. אפשר לנסות שוב מאוחר יותר.": "Can't reach GitHub right now. Try again later.",
  "מה חדש": "What's new",
  "לא מוגדר": "Not set",
  "מוגדר": "Set",
  "ריק": "Empty",
  "פעיל": "On",
  "כבוי": "Off",
  "צריך מספר": "A number is needed",
  "צריך מספר שלם": "A whole number is needed",
  "בחירה לא מוכרת": "Unknown choice",
  "הכתובת צריכה להתחיל ב-http:// או https://": "The address must start with http:// or https://",
  "אזור זמן לא מוכר": "Unknown time zone",
  "מותרים רק אותיות באנגלית, ספרות, נקודה, מקף וקו תחתון": "Only English letters, digits, dot, dash and underscore",
  "צריך למלא ערך": "A value is needed",
  "פריט ארוך מדי": "An item is too long",
  "הערך נקבע בקובץ ההגדרות בשרת": "The value is set in the server's settings file",
  "המודל כבוי או לא קיים": "The model is off or doesn't exist",
  "מודל לא מוכר": "Unknown model",
  "הגדרה לא מוכרת": "Unknown setting",
  "עוד לא זמין": "Not available yet",
  "אי אפשר לקבוע את ההגדרה הזו לצוות": "This setting can't be set per team",
  "ערך לא תקין": "Invalid value",
  "מוגדר בקובץ ההגדרות בשרת": "Set in the server's settings file",
  "הערך החדש": "The new value",
  "החלפה": "Replace",
  "הגדרה": "Set",
  "(שינוי אחד)": "(one change)",
  "השינויים האלה משפיעים על האבטחה. כל שינוי נרשם ביומן השינויים.": "These changes affect security. Every change is recorded in the change log.",
  "ערך חדש": "New value",
  "לשמור שינויים רגישים?": "Save sensitive changes?",
  "ההגדרה נשמרה.": "The setting was saved.",
  "חלק מהערכים לא תקינים. הפרטים מסומנים ליד כל הגדרה.": "Some values are invalid. The details are marked next to each setting.",
  "הערך שנשמר במסך יפסיק לחול.": "The value saved on the screen will stop applying.",
  "ההגדרה חזרה לברירת המחדל.": "The setting is back to its default.",
  "קודם שומרים את השינוי, ואז בודקים.": "Save the change first, then check.",
  "שליחת מייל ניסיון": "Send a test email",
  "לאיזו כתובת לשלוח?": "Which address should it go to?",
  "הבדיקה עברה: החיבור תקין.": "The check passed: the connection works.",
  "הקובץ לא קריא: צריך קובץ JSON שיוצא מהמסך הזה.": "Can't read the file: it must be a JSON file exported from this screen.",
  "אין מה לשנות: ההגדרות בקובץ זהות לקיימות.": "Nothing to change: the settings in the file match the current ones.",
  "הקובץ לא יובא": "The file was not imported",
  "לייבא שינוי אחד?": "Import one change?",
  "ייבוא": "Import",
  "ההגדרות יובאו.": "The settings were imported.",
  "אחרי שיוצרים את הצוות אפשר לקבוע לו הגדרות מיוחדות.": "Once the team is created, you can give it special settings.",
  "מיוחד לצוות": "Special for the team",
  "הגדרה שונתה": "Setting changed",
  "הגדרה מיוחדת לצוות": "Team's special setting",
  "הגדרות יובאו": "Settings imported",
  "גיבוי": "Backup",
  "הוסר מהמסך": "Removed from the screen",
  "הוחלף": "Replaced",
  "כמו ההגדרה הכללית": "Like the global setting",
  "גיבוי אוטומטי": "Automatic backup",
  "גיבוי ידני": "Manual backup",
  "אין ברשימת המודלים מודל של הספק הזה, ולכן אין מה לבדוק": "There is no model of this provider in the model list, so there is nothing to check",
  "חלק מהערכים לא תקינים": "Some values are invalid",
  "אין שינויים לשמור": "No changes to save",
  "הקובץ הוא לא קובץ הגדרות של FireGate": "The file isn't a FireGate settings file",
});

// texts with numbers, money or names inside. Order matters: the " · " splitter first, then specific patterns, generic ones last.
(() => {
  const t = s => (typeof I18N !== "undefined" ? I18N.t(s) : s);
  const M = "(\\$[\\d,.]+)";  // money as admin.js prints it
  const R = s => new RegExp("^" + s.replaceAll("$M", M) + "$");
  const team = (prefix, name) => (prefix ? "team " : "") + name;
  const TIERS = { "מהיר": "fast", "חכם": "smart", "הכי חזק": "strongest", "חסכוני": "lite" };
  window.EN_PATTERNS = (window.EN_PATTERNS || []).concat([
    // model display names ("Claude מהיר") inside any text: swap the name, then translate the rest
    [/^(.*?)(Claude|GPT|Gemini) (מהיר|חכם|הכי חזק|חסכוני)(.*)$/, (_, a, p, k, b) => t(a + p + " " + TIERS[k] + b)],
    // joined texts ("a · b · c"): translate each part on its own
    [/^.+ · .+$/, s => s.split(" · ").map(t).join(" · ")],
    // budgets
    [R("מתוך $M"), "of $1"],
    [R("בחודש שעבר: $M\\. אפשר לעדכן בעריכה\\."), "Last month: $1. You can change it under Edit."],
    [R("אפשר להוריד ל-$M"), "Could go down to $1"],
    [R("בקצב הנוכחי (צוות )?(.+) יוציא $M עד סוף החודש\\."), (_, p, n, m) => `At the current pace, ${team(p, n)} will spend ${m} by the end of the month.`],
    [R("בחודש שעבר (צוות )?(.+) הוציא $M\\. התקציב הנוכחי גבוה בהרבה מהצורך\\."), (_, p, n, m) => `Last month ${team(p, n)} spent ${m}. The current budget is far above what's needed.`],
    [R("לעדכן את התקציב של (צוות )?(.+)\\?"), (_, p, n) => `Update the budget for ${team(p, n)}?`],
    [R("התקציב של (צוות )?(.+) עודכן ל-$M\\."), (_, p, n, m) => `Budget for ${team(p, n)} set to ${m}.`],
    [R("התקציב של (צוות )?(.+) חזר ל-$M\\."), (_, p, n, m) => `Budget for ${team(p, n)} is back to ${m}.`],

    // the settings screen
    [/^ב-(\d+) לכל חודש, (\d\d:00)$/, "On day $1 of every month, $2"],
    [/^(\d+) צוותים עם חריג$/, "$1 teams with their own value"],
    [/^הערך נקבע בקובץ ההגדרות של השרת \((.+)\)\. כדי לשנות אותו כאן, מוחקים אותו משם ומפעילים את השער מחדש\.$/,
      "The value is set in the server's settings file ($1). To change it here, remove it there and restart the gateway."],
    [/^נדרשת הפעלה מחדש: (.+)$/, "A restart is needed: $1"],
    [/^הגיבוי נשמר: (.+)$/, "Backup saved: $1"],
    [/^גיבוי אחרון: (.+)$/, "Last backup: $1"],
    [/^(\d+) בתיקייה$/, "$1 in the folder"],
    [/^הבדיקה נכשלה \((.+)\)\.$/, "The check failed ($1)."],
    [/^יש גרסה חדשה: (.+) \(מותקנת (.+)\)\.$/, "A new version is out: $1 (installed: $2)."],
    [/^הגרסה המותקנת \((.+)\) היא העדכנית\.$/, "The installed version ($1) is the latest."],
    [/^לפחות (\d[\d.]*) תווים$/, "At least $1 characters"],
    [/^לפחות (-?\d[\d.]*)$/, "At least $1"],
    [/^לכל היותר (-?\d[\d.]*)$/, "At most $1"],
    [/^עד (\d+) תווים$/, "Up to $1 characters"],
    [/^עד (\d+) פריטים$/, "Up to $1 items"],
    [/^שם שרת לא תקין: (.+)$/, "Invalid host name: $1"],
    [/^כתובת או טווח לא תקינים: (.+)$/, "Invalid address or range: $1"],
    [/^צריך נתיב מלא: (.+)$/, "A full path is needed: $1"],
    [/^נבדק לאחרונה ב-(.+?)( \(נכשל\))?$/, (_, d, f) => `Last checked ${d}${f ? " (failed)" : ""}`],
    [/^\((\d+) שינויים\)$/, "($1 changes)"],
    [/^(\d+) הגדרות נשמרו\.$/, "$1 settings saved."],
    [/^(\d+) הגדרות שונו$/, "$1 settings changed"],
    [/^להחזיר את "(.+)" לברירת המחדל\?$/, "Return \"$1\" to its default?"],
    [/^מייל ניסיון נשלח ל-(.+)\.$/, "A test email was sent to $1."],
    [/^הבדיקה נכשלה: (.*)$/, (_, e) => "The check failed: " + t(e)],
    [/^אין מה לשנות\. (\d+) הגדרות בקובץ דולגו\.$/, "Nothing to change. $1 settings in the file were skipped."],
    [/^דולגו: (.+)$/, (_, l) => "Skipped: " + l.replace(/\(לא מוכרת\)/g, "(unknown)").replace(/\(סוד \(לא מיובא\)\)/g, "(a secret, not imported)")
      .replace(/\(עוד לא זמינה\)/g, "(not available yet)").replace(/\(נקבעת בקובץ ההגדרות בשרת\)/g, "(set in the server's settings file)")],
    [/^ערכים לא תקינים, ולכן אי אפשר לייבא: (.+)$/, (_, l) => "Invalid values, so nothing can be imported: " + l.split("; ").map(x => x.split(": ").map(t).join(": ")).join("; ")],
    [/^לייבא (\d+) שינויים\?$/, "Import $1 changes?"],
    [/^הגדרה מיוחדת לצוות: (.+)$/, "Team's own value: $1"],
    [/^כמו הכללי \((.*)\)$/, (_, v) => `Like the global setting (${t(v)})`],
    // server errors with details
    [/^שרת ה-MCP: (.*)$/, "MCP server: $1"],
    [/^(.+): לא הצלחנו לקרוא את הקובץ \(פגום או מוצפן\)$/, "$1: couldn't read the file (damaged or encrypted)"],
    [/^(.+): אין בקובץ טקסט \(קובץ סרוק צריך זיהוי טקסט קודם\)$/, "$1: no text in the file (a scanned file needs text recognition first)"],
    [/^(\d+) משתמשים עדיין מורשים להשתמש במודל\. אפשר לכבות אותו, או להסיר אותו מהמשתמשים קודם$/, "$1 users are still allowed to use the model. Turn it off, or remove it from those users first"],
    [/^לא הצלחנו לטעון את הנתונים מהשער \((.*)\)\. ייתכן שהשרת לא זמין\.$/, (_, m) => `Couldn't load data from the gateway (${t(m)}). The server may be down.`],

    // dashboard
    [R("לעומת חודש קודם \\($M\\)"), "vs. last month ($1)"],
    [/^מתוך ([\d,]+) חשבונות$/, "of $1 accounts"],
    [/^(\d+) מתוך (\d+)$/, "$1 of $2"],
    [R("(.+): התקציב האישי נגמר \\($M מתוך $M\\)\\. חסום עד ה-(\\d+) לחודש או עד הגדלת תקציב\\."), (_, n, a, b, d) => `${n}: personal budget used up (${a} of ${b}). Blocked until day ${d} of the month or a budget increase.`],
    [/^צוות (.+): תקציב הצוות נגמר\. כל חברי הצוות חסומים\.$/, "Team $1: team budget used up. All team members are blocked."],
    [/^צוות (.+): עבר (\d+)% מתקציב הצוות\.$/, "Team $1: passed $2% of the team budget."],
    [/^(.+): עבר (\d+)% מהתקציב האישי\.$/, "$1: passed $2% of the personal budget."],
    [/^(.+): החשבון נעול אחרי (\d+) סיסמאות שגויות\. איפוס סיסמה משחרר אותו\.$/, "$1: account locked after $2 wrong passwords. Resetting the password unlocks it."],
    [/^(.+): המפתח לאפליקציות פג תוקף, ולכן הבקשות שלו נחסמות\. צריך להנפיק מפתח חדש\.$/, "$1: the API key has expired, so its requests are blocked. Issue a new key."],
    [/^(.+): המפתח לאפליקציות יפוג בעוד (\d+) ימים\. כדאי להנפיק מפתח חדש ולהעביר אותו לאפליקציה\.$/, "$1: the API key expires in $2 days. Issue a new key and give it to the app."],
    [/^(.+): המפתח לאפליקציות בשימוש כבר (\d+) ימים\. מומלץ להחליף מפתח כל (\d+) יום\.$/, "$1: the API key has been in use for $2 days. Replacing keys every $3 days is recommended."],
    [R("(.+): הוצאה חריגה בשעה האחרונה \\($M, בדרך כלל $M לשעה\\)\\. כדאי לבדוק שהמפתח לא דלף\\."), "$1: unusual spending in the last hour ($2, usually $3 per hour). Check that the key hasn't leaked."],
    [/^כל (\d+) השורות ביומן השינויים שלמות: אף אחת לא נערכה או נמחקה מחוץ למערכת\.$/, "All $1 rows of the change log are intact: none was edited or deleted outside the system."],
    [/^השורה מ-(.+) ביומן השינויים נערכה, נמחקה או נוספה מחוץ למערכת\. כל מה שאחריה לא מאומת\.$/, "The change-log row from $1 was edited, deleted or added outside the system. Nothing after it can be trusted."],
    [/^(\d+) פריטים$/, "$1 items"],
    [/^(\d+)% מהתקציב$/, "$1% of budget"],
    [R("צפי $M"), "Projected $1"],
    [R("הוצאה מצטברת: $M עד היום, צפי $M לסוף החודש, החודש הקודם $M"), "Cumulative spend: $1 so far, projected $2 by month end, last month $3"],
    [R("תקציבי הצוותים $M"), "Team budgets $1"],
    [R("החודש: $M"), "This month: $1"],
    [R("צפי לסוף החודש: $M"), "Projected by month end: $1"],
    [R("החודש הקודם: $M"), "Last month: $1"],
    [/^(.+): (\d+) משתמשים$/, (_, b, n) => `${t(b)}: ${n} users`],
    [/^עד 50%: .*$/, s => s.replace("עד 50%", "Under 50%").replace("מעל 150%", "Over 150%")],
    [/^יום (\S+), (.+)$/, (_, d, h) => `${t(d)}, ${h}`],
    [R("(אחר|בלי צוות): (.*)"), (_, k, v) => `${t(k)}: ${v}`],
    [/^([\d,]+) בקשות$/, "$1 requests"],

    // users and keys
    [/^(\d+) לדקה$/, "$1/min"],
    [/^([\d,]+) נכנסו$/, "$1 in"],
    [/^([\d,]+) יצאו$/, "$1 out"],
    [/^(\d+) שיחות שמורות$/, "$1 saved chats"],
    [/^(\d+) בארכיון$/, "$1 archived"],
    [/^מוצגות (\d+) הבקשות האחרונות\. כל השאלות נשמרות במסד הנתונים\.$/, "Showing the last $1 requests. Every question is kept in the database."],
    [/^עריכת צוות (.+)$/, "Edit team $1"],
    [/^עריכת (.+)$/, "Edit $1"],
    [/^להעביר את צוות (.+) לארכיון\?$/, "Move team $1 to the archive?"],
    [/^להעביר את המקור "(.+)" לארכיון\?$/, "Move the source \"$1\" to the archive?"],
    [/^להעביר את (.+) לארכיון\?$/, "Move $1 to the archive?"],
    [/^צוות (.+) הועבר לארכיון\.$/, "Team $1 moved to the archive."],
    [/^המקור (.+) הועבר לארכיון\.$/, "Source $1 moved to the archive."],
    [/^(.+) הועבר לארכיון\.$/, "$1 moved to the archive."],
    [/^(.+) שוחזר מהארכיון\.$/, "$1 restored from the archive."],
    [/^העברה לארכיון של (.+)$/, "Move $1 to the archive"],
    [/^(\d+) הועברו לארכיון$/, "$1 moved to the archive"],
    [/^במקור (.+)$/, "in source $1"],
    [/^למחוק את צוות (.+)\?$/, "Delete team $1?"],
    [/^למחוק את המקור "(.+)"\?$/, "Delete the source \"$1\"?"],
    [/^למחוק את (.+)\?$/, "Delete $1?"],
    [/^להסיר את (.+)\?$/, "Remove $1?"],
    [/^להנפיק מפתח חדש ל-(.+)\? המפתח הקודם יפסיק לעבוד מיד\.$/, "Issue a new key for $1? The old key stops working right away."],
    [/^לבטל את המפתח של (.+)\? אפליקציות שמשתמשות בו יפסיקו לעבוד מיד\.$/, "Revoke $1's key? Apps that use it stop working right away."],
    [/^השינויים ב-(.+) נשמרו\.$/, "Changes to $1 saved."],
    [/^צוות (.+) נמחק\.$/, "Team $1 deleted."],
    [/^צוות (.+) עודכן\.$/, "Team $1 updated."],
    [/^המקור (.+) נמחק\.$/, "Source $1 deleted."],
    [/^המקור (.+) עודכן\.$/, "Source $1 updated."],
    [/^(.+) נמחק\.$/, "$1 deleted."],
    [/^(.+) נוצר\.$/, "$1 created."],
    [/^(.+) הוסר\.$/, "$1 removed."],
    [/^(.+) עודכן\.$/, "$1 updated."],
    [/^(.+) כובה\.$/, "$1 turned off."],
    [/^(.+) הודלק\.$/, "$1 turned on."],
    [/^(.+) נוסף\. אפשר ללחוץ "בדיקה" כדי לוודא שהוא עובד\.$/, "$1 added. Click \"Test\" to make sure it works."],
    [/^(.+) הוא עכשיו ברירת המחדל\.$/, "$1 is now the default."],
    [/^השאלה והתשובה של (.+), (.+)$/, "$1's question and answer, $2"],

    // change log details
    [R("תקציב $M ← $M"), "Budget $1 → $2"],
    [R("תקציב $M"), "Budget $1"],
    [/^מודלים: (.*)$/, "Models: $1"],
    [/^(\d+) בקשות לדקה$/, "$1 requests per minute"],
    [/^(מחיר נכנס|מחיר יוצא|מחיר מטמון|גיבוי|שם אצל הספק|ספק|פעיל): (.*) ← (.*)$/, (_, k, a, b) =>
      `${{ "מחיר נכנס": "Input price", "מחיר יוצא": "Output price", "מחיר מטמון": "Cache price", "גיבוי": "Backup",
        "שם אצל הספק": "Provider model ID", "ספק": "Provider", "פעיל": "On" }[k]}: ${a} → ${b}`],
    [/^גישה: (.*)$/, (_, v) => `Access: ${v === "אף אחד" ? "no one" : t(v)}`],
    [/^(\d+) קבצים, (\d+) דולגו$/, "$1 files, $2 skipped"],
    [/^(\d+) קבצים$/, "$1 files"],

    // models
    [/^לכבות את (.+)\?$/, "Turn off $1?"],
    // models on the company's own server, and speed
    [/^(.+) \(מקומי\)( \(.*\))?$/, (_, n, rest) => `${t(n)} (local)${rest || ""}`],
    [/^השרת לא עונה: (.*)$/, (_, e) => `The server isn't answering: ${t(e)}`],
    [/^השרת עונה: (\d+) מודלים זמינים \((\d+) מילישניות\)\.$/, "The server answers: $1 models available ($2 ms)."],
    [/^(.+) נוסף לרשימת המודלים, במחיר 0\. אפשר לשנות מחיר בעריכה, ולהתיר אותו למשתמשים\.$/,
      "$1 was added to the model list at price 0. You can change the price under Edit, and allow it for users."],
    [/^הכתובת (.+) חסומה לשרת המודלים המקומי \(כתובת פנימית של ענן, או המחשב הזה עצמו\)$/,
      "The address $1 is blocked for the local model server (a cloud-internal address, or this machine itself)"],
    [/^([\d.]+) שנ׳$/, "$1 s"],
    [/^([\d.]+) דק׳$/, "$1 min"],
    [/^בשעה האחרונה: ([\d.]+ (?:שנ׳|דק׳)) ב-95% מהתשובות$/, (_, a) => `In the last hour: ${t(a)} for 95% of answers`],
    [/^ספק (.+) איטי מהרגיל: (.+)\.$/, (_, p, rest) => `${t(p)} is slower than usual: ` + rest.split("; ").map(x => x.replace(
      /^(.+) ענה בשעה האחרונה תוך ([\d.]+ (?:שנ׳|דק׳)) \(95% מהתשובות\), בדרך כלל ([\d.]+ (?:שנ׳|דק׳))$/, (__, m, a, b) => `${t(m)} took up to ${t(a)} in the last hour (95% of answers), usually ${t(b)}`)).join("; ") + "."],
    [/^(\d+) ערכים רגישים, לא הוסתרו$/, "$1 sensitive values, not masked"],
    [/^(\d+) משתמשים ואפליקציות מורשים להשתמש בו\. מרגע הכיבוי הם יקבלו הודעה שהמודל כבוי, עד שתדליקו אותו שוב\.$/, "$1 users and apps are allowed to use it. Once it's off they get a message that the model is off, until you turn it back on."],
    [/^(\d+) משתמשים עדיין מורשים להשתמש בו, ולכן אי אפשר להעביר אותו לארכיון\. אפשר לכבות אותו, או להסיר אותו מהמשתמשים קודם\.$/, "$1 users are still allowed to use it, so it can't be archived. Turn it off, or remove it from those users first."],
    [/^(\d+) משתמשים עדיין מורשים להשתמש בו, ולכן אי אפשר למחוק\. אפשר לכבות אותו, או להסיר אותו מהמשתמשים קודם\.$/, "$1 users are still allowed to use it, so it can't be deleted. Turn it off, or remove it from those users first."],
    [/^(.+) עונה: החיבור תקין \((\d+) מילישניות\)\.$/, "$1 answers: connection OK ($2 ms)."],
    [/^(.+) לא עונה: אין מפתח של (.+) בקובץ \.env$/, "$1 isn't answering: no $2 key in the .env file"],
    [/^(.+) לא עונה: (.*)$/, (_, m, e) => `${m} isn't answering: ${t(e)}`],
    [/^([\d,]+) שאלות נותבו החודש$/, "$1 questions routed this month"],
    [/^(.+) פעיל$/, "$1 on"],
    [/^מחיקת (.+)$/, "Delete $1"],
    [R("חיסכון מהמטמון החודש: $M"), "Cache savings this month: $1"],
    [/^(.+): מחובר$/, (_, p) => `${t(p)}: connected`],
    [/^(.+): חסר מפתח$/, "$1: key missing"],
    [/^(.+): חסרה כתובת$/, (_, p) => `${t(p)}: address missing`],
    [/^גיבוי: (.+) לא זמין$/, "backup: $1 unavailable"],
    [/^גיבוי: (.+)$/, "Backup: $1"],
    [/^ענה (\d+) פעמים החודש$/, "answered $1 times this month"],
    [R("חסך $M במטמון"), "Saved $1 via cache"],
    [R("$M לבקשה"), "$1 per request"],
    [/^(חלק מהבקשות|חלק מההוצאה): (\d+)%$/, (_, k, p) => `${t(k)}: ${p}%`],
    [/^(.+): (\d+)% מהבקשות, (\d+)% מההוצאה$/, "$1: $2% of requests, $3% of spend"],
    [/^הוצאה יומית לפי מודל ב-30 הימים האחרונים\. הפירוט המלא בטבלת המודלים שמתחת\.$/, "Daily spend by model over the last 30 days. Full details in the models table below."],
    // automatic-choice reason with a fallback note (server)
    [/^(.+) \(המודל המתאים לא זמין לך\)$/, (_, r) => `${t(r)} (the right model isn't available to you)`],
    [/^(.+) \(המהיר מבין המתאימים\)$/, (_, r) => `${t(r)} (the fastest suitable one)`],

    // security
    [/^(\d+) ערכים הוסתרו$/, "$1 values masked"],
    [/^(\d+) מפתחות הוסתרו$/, "$1 keys masked"],
    [/^קישורים: (.+)$/, "Links: $1"],
    [R("שעה אחרונה $M, בדרך כלל $M לשעה"), "Last hour $1, usually $2 per hour"],
    [/^(\d+) טוקנים ליום$/, "$1 tokens per day"],
    [/^המפתח בתוקף עד (.+)$/, "key valid until $1"],
    [/^(עקיפת הוראות|מידע רגיש): (לחסום|רק לרשום|להסתיר)$/, (_, k, v) =>
      `${k === "מידע רגיש" ? "Sensitive data" : "Instruction override"}: ${{ "לחסום": "block", "רק לרשום": "log only", "להסתיר": "mask" }[v]}`],
    [/^קובץ: (.+)$/, "File: $1"],
    [/^כתובת: (.+)$/, "IP: $1"],
    [/^שם שרת: (.+)$/, "Host: $1"],
    [/^אתר מקור: (.+)$/, "Origin: $1"],
    [/^ל-(\d+) דקות$/, "for $1 minutes"],
    [/^(\d+) מפתחות API בלי הגבלת קצב\. מפתח שדלף יכול לרוקן תקציב מהר\.$/, "$1 API keys have no rate limit. A leaked key can drain a budget fast."],
    [/^ספקים מחוברים: (.+)$/, "Connected providers: $1"],

    // knowledge sources
    [/^חיפוש לפי משמעות: פעיל \((.+)\)$/, "Meaning search: on ($1)"],
    [/^([\d,]+) מתוך ([\d,]+) קטעים מאונדקסים\. .*$/, "$1 of $2 passages indexed. A question about \"vacation\" also finds a document that says \"time off\"."],
    [/^לאנדקס ([\d,]+) קטעים$/, "Index $1 passages"],
    [/^([\d.]+[MK]?) תווים$/, "$1 chars"],
    [/^(\d+) מסמכים$/, "$1 documents"],
    [/^(.+): מחובר( ל-(.+))?\.$/, (_, n, __, s) => `${n}: connected${s ? ` to ${s}` : ""}.`],
    [/^(.+): לא מחובר \((.*)\)$/, "$1: not connected ($2)"],
    [/^סונכרנו (\d+) קבצים(.*)$/, (_, n, rest) => `Synced ${n} files` + rest
      .replace(/^\. (\d+) דולגו \(לא טקסט, או גדולים מ-2MB\)/, ". $1 skipped (not text, or larger than 2MB)")
      .replace(/\. (\d+) שהקובץ שלהם נעלם הועברו לארכיון/, ". $1 whose file is gone were moved to the archive")
      .replace(/\. (\d+) לא נקלטו בגלל תוכן חשוד: /, ". $1 refused for suspicious content: ")],
    [/^אפשר להעלות קבצים עד (\d+)MB\. גדולים מדי: (.+)$/, "Files up to $1MB can be uploaded. Too big: $2"],
    [/^(.+): (.*)\. מסמך כזה יגיע לכל מי שמחפש במקור\. ההחלטה תירשם ביומן האבטחה\.$/, (_, f, k) =>
      `${f}: ${k.split(", ").map(t).join(", ")}. A document like this reaches everyone who searches the source. The decision is recorded in the security log.`],
    [/^הועלו (\d+) קבצים ל"(.+)"\.$/, "Uploaded $1 files to \"$2\"."],
    [/^לא הצלחנו להתחבר: (.*)$/, "Couldn't connect: $1"],
    [/^מחובר( ל-(.+))?: (\d+) כלים, (\d+) מסמכים\.$/, (_, __, s, n, d) => `Connected${s ? ` to ${s}` : ""}: ${n} tools, ${d} documents.`],

    // savings recommendations (the server writes them in Hebrew)
    [R("(צוות )?(.+) שולח שאלות קצרות למודל החזק (.+)\. מעבר ל-(.+) בשאלות כאלה יחסוך כ-$M בחודש\."), (_, p, n, a, b, m) =>
      `${p ? "Team " : ""}${n} sends short questions to the strong model ${a}. Moving such questions to ${b} would save about ${m} a month.`],
    [/^(\d+)% מההוצאה של צוות (.+) הולכים ל-(.+), המודל היקר ביותר של הספק\. כדאי לבדוק אם חלק מהעבודה מתאים ל-(.+)\.$/,
      "$1% of team $2's spend goes to $3, the provider's most expensive model. Check whether some of the work suits $4."],
    [/^המודל (.+) פעיל, אבל אף אחד לא השתמש בו ב-30 הימים האחרונים\. כדאי לכבות אותו עד שיהיה בו צורך\.$/,
      "$1 is on, but nobody has used it in the last 30 days. Turn it off until it's needed."],
    [R("אפשר לחסוך עד $M בחודש"), "Up to $1 a month could be saved"],
    [/^לפי 30 הימים האחרונים\. "שאלה קצרה" היא עד ([\d,]+) טוקנים נכנסים ועד ([\d,]+) יוצאים\. .*$/,
      "Based on the last 30 days. A \"short question\" is up to $1 tokens in and $2 out. The saving is priced at the cheap model's rates, per month."],

    // teams, chargeback, monthly summary
    [/^(\d+) מודלים מותרים$/, "$1 models allowed"],
    [/^מרכז עלות (.+)$/, "Cost center $1"],
    [/^חשבון (.+)$/, "GL account $1"],
    [/^נמענים: (.+)$/, "Recipients: $1"],
    [/^(\d+) נמענים$/, "$1 recipients"],
    [/^נשלח לאחרונה: הסיכום של (.+)$/, "Last sent: the summary for $1"],
    [/^הסיכום של (.+) יישלח עכשיו לנמענים השמורים: (.+)$/, "The summary for $1 will be sent now to the saved recipients: $2"],
    [/^הסיכום של (.+) נשלח\.$/, "The summary for $1 was sent."],
    [/^הסיכום של (.+)$/, "Summary for $1"],
    [/^ניסיון (\d+) מתוך (\d+)$/, "try $1 of $2"],
    [/^כתובת מייל לא תקינה: (.*)$/, "Not a valid email address: $1"],
    [/^השליחה נכשלה: (.*)$/, "Sending failed: $1"],

    // generic, kept late so the specific ones above win
    [/^צוות (.+)$/, "Team $1"],
    [/^(.+)\?$/, (_, s) => { const v = t(s); return v === s ? s + "?" : v + "?"; }],
  ]);
})();

// static prose split across inline tags
window.EN_HTML = Object.assign(window.EN_HTML || {}, {
  "#keyDialog p.small": "The key is shown <b>only once</b>. The gateway keeps only a one-way fingerprint of it (SHA-256), so it can't be recovered. Copy it and hand it over now.",
});
