// English texts for the interface (see i18n.js): the admin screen, the shared side menu, the shared dialogs and toasts,
// and the Hebrew texts the server sends (health checks, automatic-choice reasons, default model names)
window.EN = Object.assign(window.EN || {}, {
  // side menu, shared by every page
  "ניווט": "Navigation",
  "ראשי": "Main",
  "לוח בקרה": "Dashboard",
  "ניהול": "Manage",
  "משתמשים ומפתחות": "Users and keys",
  "מודלים": "Models",
  "צוותים": "Teams",
  "מקורות מידע": "Knowledge sources",
  "בקרה": "Monitor",
  "דוחות": "Reports",
  "אבטחה": "Security",
  "יומן שאלות": "Question log",
  "יומן שינויים": "Change log",
  "עובדים": "Employees",
  "מסך הצ'אט": "Chat",
  "תיעוד": "Docs",
  "הצגה או הסתרה של התפריט": "Show or hide the menu",
  "סגירת התפריט": "Close the menu",
  "מיקום": "Breadcrumb",
  "רענון": "Refresh",
  "מ": "A",
  "מנהל": "Admin",
  // shared dialogs and toasts (ui.js)
  "סגירת ההודעה": "Dismiss",
  "אישור": "OK",
  "ביטול": "Cancel",
  "סגירה": "Close",
  "שמירה": "Save",

  // page title, footer, login
  "FireGate · ניהול": "FireGate · Admin",
  "FireGate · ניהול שימוש בבינה מלאכותית": "FireGate · AI usage management",
  "מסך הצ'אט לעובדים": "Employee chat",
  "כניסה מבחוץ": "Sign in from outside",
  "מתוך רשת המשרד אין צורך בסיסמה. מבחוץ צריך את סיסמת המנהל.": "Inside the office network no password is needed. From outside, enter the admin password.",
  "סיסמת מנהל": "Admin password",
  "כניסה": "Sign in",
  "סיסמה שגויה": "Wrong password",

  // dashboard
  "משתמש חדש": "New user",
  "צעדים ראשונים": "Getting started",
  "דורש טיפול": "Needs attention",
  "הוצאה יומית": "Daily spend",
  "30 הימים האחרונים": "Last 30 days",
  "הוצאה לפי מודל": "Spend by model",
  "החודש": "This month",
  "המשתמשים שהוציאו הכי הרבה": "Top spenders",
  "שם": "Name",
  "צוות": "Team",
  "בקשות": "Requests",
  "הוצאה": "Spend",
  "מצב תקציב": "Budget status",
  "צוותים מול תקציב": "Teams vs. budget",
  "הוצאה מצטברת החודש": "Cumulative spend this month",
  "מול החודש הקודם ומול תקציבי הצוותים": "Against last month and the team budgets",
  "צפי ניצול התקציב": "Projected budget use",
  "כמה משתמשים יסיימו את החודש בכל טווח": "How many users will end the month in each range",
  "מתי שואלים": "When people ask",
  "בקשות לפי יום ושעה, 4 השבועות האחרונים": "Requests by day and hour, last 4 weeks",
  "הוצאה חודשית לפי צוות": "Monthly spend by team",
  "ארבעת החודשים האחרונים": "Last four months",
  "הוצאה החודש": "Spent this month",
  "השבוע לעומת השבוע הקודם": "This week vs. last week",
  "צפי לסוף החודש": "Projected for the month",
  "בקשות החודש": "Requests this month",
  "משתמשים פעילים": "Active users",
  "חדש": "New",
  "לחבר ספק: להכניס מפתח של Anthropic, ‏OpenAI או Google לקובץ .env ולהפעיל את השער מחדש": "Connect a provider: put an Anthropic, OpenAI or Google key in the .env file and restart the gateway",
  "ליצור צוות עם תקציב חודשי": "Create a team with a monthly budget",
  "ליצור משתמש ראשון": "Create the first user",
  "לשאול שאלה ראשונה במסך הצ'אט": "Ask a first question in the chat",
  "לעשות את זה": "Do it",
  "לפרטים": "Details",
  "הכל תקין: אין חריגות תקציב ואין הערות אבטחה פתוחות.": "All good: no budget overruns and no open security notes.",
  "חסום": "Blocked",
  "אין שימוש החודש": "No usage this month",
  "אין צוותים עדיין": "No teams yet",
  "לנסות שוב": "Try again",
  "עוד אין שימוש ב-30 הימים האחרונים": "No usage in the last 30 days yet",
  "הוצאה יומית ב-30 הימים האחרונים": "Daily spend over the last 30 days",
  "תקציבי הצוותים": "Team budgets",
  "עד 50%": "Under 50%",
  "מעל 150%": "Over 150%",
  "ראשון": "Sun", "שני": "Mon", "שלישי": "Tue", "רביעי": "Wed", "חמישי": "Thu", "שישי": "Fri", "שבת": "Sat",
  "מפת חום של בקשות לפי יום בשבוע ושעה": "Heat map of requests by weekday and hour",
  "מעט": "Less",
  "הרבה": "More",
  "אחר": "Other",
  "אין שימוש עדיין": "No usage yet",
  "חלוקת ההוצאה לפי מודל": "Spend split by model",
  "סה\"כ החודש": "Total this month",
  "סה\"כ": "Total",

  // users and keys
  "חיפוש לפי שם או צוות": "Search by name or team",
  "חיפוש משתמשים": "Search users",
  "\"צפי\" הוא כמה המשתמש יוציא עד סוף החודש בקצב הנוכחי. \"מומלץ\" הוא הגבוה מבין הצפי לבין החודש הקודם, ועוד 20% מרווח.": "\"Projected\" is what the user will spend by the end of the month at the current pace. \"Suggested\" is the higher of the projection and last month, plus a 20% margin.",
  "צפי": "Projected",
  "תקציב מומלץ": "Suggested budget",
  "גישה": "Access",
  "פעולות": "Actions",
  "ללא תקרה": "No cap",
  "מתאים": "Fits",
  "להחיל": "Apply",
  "להעלות את התקציב לסכום המומלץ לפני שהחשבון ייחסם": "Raise the budget to the suggested amount before the account gets blocked",
  "עדכון התקציב": "Update budget",
  "ביטול השינוי": "Undo",
  "יעבור את התקציב": "Will exceed budget",
  "צ'אט": "Chat",
  "נעול": "Locked",
  "עריכה": "Edit",
  "מחיקה": "Delete",
  "הכניסה לצ'אט והמפתח יפסיקו לעבוד מיד. היסטוריית השאלות נשארת ביומן.": "Chat sign-in and the key stop working right away. The question history stays in the log.",
  "אין משתמשים שמתאימים לחיפוש.": "No users match the search.",
  "אין משתמשים עדיין. לחצו על \"משתמש חדש\".": "No users yet. Click \"New user\".",
  "חכם": "smart",
  "מהיר": "fast",
  "כבוי": "Off",

  // user dialog
  "מי": "Who",
  "שם (עובד, אפליקציה או לקוח)": "Name (employee, app or customer)",
  "מגבלות": "Limits",
  "תקציב חודשי ($)": "Monthly budget ($)",
  "בקשות לדקה (0 = ללא הגבלה)": "Requests per minute (0 = no limit)",
  "מודלים מותרים": "Allowed models",
  "מחיר לכל מיליון טוקנים: נכנס / יוצא": "Price per million tokens: in / out",
  "ליצור מפתח לאפליקציות (API)": "Create an API key for apps",
  "בלי צוות": "No team",
  "סיסמה חדשה לצ'אט (ריק = בלי שינוי; גם משחרר נעילה)": "New chat password (empty = no change; also unlocks the account)",
  "סיסמה לכניסה לצ'אט (לפחות 8 תווים; ריק = בלי צ'אט)": "Chat sign-in password (at least 8 characters; empty = no chat)",
  "מפתח לאפליקציות (API)": "API key for apps",
  "אין מפתח": "No key",
  "מפתח חדש": "New key",
  "יצירת מפתח": "Create key",
  "ביטול מפתח": "Revoke key",
  "מפתח חדש?": "New key?",
  "יצירת מפתח?": "Create key?",
  "ביטול מפתח?": "Revoke key?",
  "המפתח החדש": "The new key",
  "העתקה": "Copy",
  "הועתק ✓": "Copied ✓",

  // teams
  "צוות חדש": "New team",
  "כשתקציב הצוות נגמר, כל חברי הצוות נחסמים, גם אם נשאר להם תקציב אישי. תקציב צוות 0 = בלי תקרה לצוות.": "When the team budget runs out, every team member is blocked, even if they have personal budget left. Team budget 0 = no team cap.",
  "חברים": "Members",
  "סכום תקציבי החברים": "Sum of member budgets",
  "החברים יישארו בלי צוות, והתקציב של הצוות יימחק. ההיסטוריה ביומן נשארת.": "Members will be left without a team and the team budget is deleted. The log history stays.",
  "מחיקת הצוות": "Delete team",
  "אין צוותים עדיין. לחצו על \"צוות חדש\".": "No teams yet. Click \"New team\".",
  "שם הצוות": "Team name",
  "תקציב חודשי לצוות ($, 0 = ללא תקרה)": "Monthly team budget ($, 0 = no cap)",
  "הצוות נוצר.": "Team created.",

  // models
  "מודל חדש": "New model",
  "כל מודל שעובדים ואפליקציות יכולים להשתמש בו. מודל כבוי נחסם אצל כולם מיד, גם אם הותר להם. המחיר קובע איך מחושבת העלות של כל שאלה, אז כדאי לעדכן אותו כשהספק משנה מחיר.": "Every model employees and apps can use. A model that is off is blocked for everyone right away, even if they were allowed it. The price sets how each question's cost is calculated, so update it when the provider changes prices.",
  "בחירה אוטומטית של מודל": "Automatic model choice",
  "כשעובד בוחר \"אוטומטי\" בצ'אט, השער שולח שאלות קצרות ופשוטות למודל הזול, וקוד, ניתוח, השוואה, טקסט ארוך או שיחה ארוכה למודל החזק. הסיבה לבחירה מוצגת לעובד ונרשמת ביומן.": "When an employee picks \"Automatic\" in the chat, the gateway sends short, simple questions to the cheap model, and code, analysis, comparisons, long text or long conversations to the strong model. The reason for the choice is shown to the employee and logged.",
  "בחירה אוטומטית פעילה": "Automatic choice on",
  "פעיל": "On",
  "מודל זול": "Cheap model",
  "מודל חזק": "Strong model",
  "הוצאה יומית לפי מודל": "Daily spend by model",
  "בקשות מול הוצאה": "Requests vs. spend",
  "כמה מהבקשות עוברות בכל מודל, וכמה מהכסף. פער גדול = מודל יקר לבקשה.": "Each model's share of requests and of money. A big gap = a model that is expensive per request.",
  "חלק מהבקשות": "Share of requests",
  "חלק מההוצאה (בצבע המודל)": "Share of spend (in the model's color)",
  "חלק מההוצאה": "Share of spend",
  "מודל": "Model",
  "ספק": "Provider",
  "מחיר למיליון טוקנים": "Price per million tokens",
  "שימוש החודש": "Usage this month",
  "משתמשים": "Users",
  "ברירת מחדל": "Default",
  "כיבוי": "Turn off",
  "אף משתמש לא מורשה להשתמש בו כרגע.": "No user is allowed to use it right now.",
  "הגדרות הבחירה האוטומטית נשמרו.": "Automatic choice settings saved.",
  "חלקים חוזרים בשיחות נקראו מהמטמון של הספק במחיר מוזל": "Repeated parts of conversations were read from the provider's cache at a discount",
  "מפתחות ספקים:": "Provider keys:",
  "יש מפתח בקובץ .env": "Key found in the .env file",
  "אין מפתח בקובץ .env: המודלים של הספק הזה לא יעבדו": "No key in the .env file: this provider's models won't work",
  "הכינוי · השם אצל הספק": "Alias · provider's model ID",
  "אין מפתח לספק הזה": "No key for this provider",
  "לקבוע": "Set",
  "המודל שנבחר אוטומטית בצ'אט ומסומן למשתמש חדש": "The model picked by default in the chat and checked for new users",
  "בדיקה": "Test",
  "שולח שאלה קצרה לספק ובודק שהמפתח והשם עובדים": "Sends a short question to the provider to check that the key and model ID work",
  "המודל יימחק מהרשימה. השאלות שנשאלו בו נשארות ביומן.": "The model is removed from the list. Questions asked with it stay in the log.",
  "אין מודלים. לחצו על \"מודל חדש\".": "No models. Click \"New model\".",
  "בלי גיבוי": "No backup",

  // model dialog
  "זיהוי": "Identity",
  "כינוי (מה שאפליקציות שולחות בשדה model)": "Alias (what apps send in the model field)",
  "שם לתצוגה (מה שעובדים רואים בצ'אט)": "Display name (what employees see in the chat)",
  "אצל הספק": "At the provider",
  "שם המודל אצל הספק": "Provider's model ID",
  "מחיר לטוקנים נכנסים ($ למיליון)": "Input token price ($ per million)",
  "מחיר לטוקנים יוצאים ($ למיליון)": "Output token price ($ per million)",
  "מחיר לטוקנים שנקראים מהמטמון של הספק ($ למיליון; ריק = עשירית ממחיר הנכנסים)": "Price for tokens read from the provider's cache ($ per million; empty = a tenth of the input price)",
  "את השם המדויק והמחירים מעתיקים מעמוד המחירים של הספק.": "Copy the exact model ID and prices from the provider's pricing page.",
  "כשהספק לא זמין": "When the provider is down",
  "מודל גיבוי": "Backup model",
  "אם הספק עמוס או לא עונה, השאלה עוברת אוטומטית למודל הגיבוי ומחויבת לפי המחיר שלו. באפליקציות זה עובד רק בין מודלים באותו פורמט: Claude עם Claude, או GPT עם Gemini.": "If the provider is overloaded or not answering, the question moves automatically to the backup model and is billed at its price. For apps this only works between models with the same format: Claude with Claude, or GPT with Gemini.",
  "פעיל: אפשר להשתמש בו": "On: available for use",

  // error messages (admin.js turns the server's English errors into Hebrew first)
  "הכינוי צריך להיות 2 עד 40 אותיות אנגליות קטנות, ספרות, נקודה, מקף או קו תחתון": "The alias must be 2 to 40 lowercase English letters, digits, dot, dash or underscore",
  "ספק לא מוכר": "Unknown provider",
  "צריך למלא את שם המודל אצל הספק": "Fill in the provider's model ID",
  "המחיר לא יכול להיות שלילי": "The price can't be negative",
  "זה מודל ברירת המחדל. קודם קובעים ברירת מחדל אחרת, ואז אפשר לכבות אותו": "This is the default model. Set another default first, then you can turn it off",
  "זה מודל ברירת המחדל. קודם קובעים ברירת מחדל אחרת": "This is the default model. Set another default first",
  "מודל הגיבוי צריך להיות מודל אחר מהרשימה": "The backup model must be another model from the list",
  "חיפוש לפי משמעות צריך מפתח של OpenAI או Google בקובץ .env": "Meaning search needs an OpenAI or Google key in the .env file",
  "קריאת PDF צריכה את הספרייה pypdf בשרת": "Reading PDF needs the pypdf package on the server",
  "כתובת שרת ה-MCP צריכה להתחיל ב-http:// או https://": "The MCP server address must start with http:// or https://",
  "צריך לבדוק חיבור ולבחור את כלי החיפוש": "Test the connection and choose the search tool",
  "אפשר לסנכרן רק תיקייה או שרת MCP במצב סנכרון": "Only folders and MCP servers in sync mode can be synced",
  "קודם מדליקים את המודל, ואז אפשר לקבוע אותו כברירת מחדל": "Turn the model on first, then you can make it the default",
  "אין מה לעדכן": "Nothing to update",
  "צריך לבחור לפחות מודל אחד": "Pick at least one model",
  "הסיסמה צריכה להיות באורך 8 תווים לפחות": "The password must be at least 8 characters",
  "התקציב לא יכול להיות שלילי": "The budget can't be negative",
  "צריך למלא שם": "Fill in a name",
  "צריך סיסמה לצ'אט, מפתח API, או את שניהם": "Give a chat password, an API key, or both",
  "השם הזה כבר קיים": "That name already exists",
  "התיקייה לא נמצאה בשרת": "The folder was not found on the server",

  // knowledge sources
  "מקור חדש": "New source",
  "מסמכים של החברה שהצ'אט מחפש בהם ומצטט מהם. כל עובד רואה רק מקורות שהצוות שלו קיבל גישה אליהם. אפשר להעלות PDF, ‏Word וקבצי טקסט (Markdown, CSV, HTML ועוד), או לחבר תיקייה בשרת שמסתנכרנת בלחיצה.": "Company documents the chat searches and quotes. Each employee only sees sources their team has access to. You can upload PDF, Word and text files (Markdown, CSV, HTML and more), or connect a server folder that syncs with one click.",
  "חיפוש לפי משמעות: כבוי": "Meaning search: off",
  "צריך מפתח של OpenAI או Google בקובץ ‎.env. בינתיים החיפוש לפי מילים בלבד.": "Needs an OpenAI or Google key in the .env file. Until then search is by words only.",
  "קריאת PDF לא זמינה בשרת הזה (חסרה הספרייה pypdf).": "PDF reading isn't available on this server (the pypdf package is missing).",
  "האינדקס עודכן.": "Index updated.",
  "כל העובדים": "All employees",
  "אף אחד עוד לא קיבל גישה": "No one has access yet",
  "הסרה": "Remove",
  "המסמך לא יופיע יותר בחיפוש בצ'אט.": "The document will no longer show up in chat search.",
  "תיקייה בשרת": "Server folder",
  "קבצים שהועלו": "Uploaded files",
  "שרת MCP": "MCP server",
  "סנכרון מסמכים": "Document sync",
  "חיפוש חי": "Live search",
  "גישה:": "Access:",
  "בדיקת חיבור": "Test connection",
  "העלאת קבצים": "Upload files",
  "סנכרון עכשיו": "Sync now",
  "כל המסמכים שבו יימחקו מהשער ולא יופיעו בצ'אט. קבצים בתיקייה בשרת עצמו לא נמחקים.": "All its documents are deleted from the gateway and won't appear in the chat. Files in the server folder itself are not deleted.",
  "מחיקת המקור": "Delete source",
  "סנכרון אחרון:": "Last sync:",
  "עוד לא סונכרן": "Not synced yet",
  "רשימת המסמכים": "Document list",
  "המקור הזה לא שומר מסמכים: בכל שאלה השער שואל את השרת בזמן אמת, ומסנן את התשובה.": "This source stores no documents: on each question the gateway asks the server live and filters the answer.",
  "לחצו על \"סנכרון עכשיו\" כדי לקרוא את המסמכים": "Click \"Sync now\" to read the documents",
  "עוד אין מסמכים. לחצו על \"העלאת קבצים\".": "No documents yet. Click \"Upload files\".",
  "אין מקורות מידע עדיין. לחצו על \"מקור חדש\".": "No knowledge sources yet. Click \"New source\".",
  "נמצא תוכן חשוד בקובץ": "Suspicious content found in the file",
  "להעלות בכל זאת": "Upload anyway",
  "מקור מידע חדש": "New knowledge source",
  "שמור. ריק = בלי שינוי": "Saved. Empty = no change",
  "המקור נוצר.": "Source created.",
  // source dialog
  "שם המקור": "Source name",
  "תיאור קצר (העובדים רואים אותו)": "Short description (employees see it)",
  "סוג": "Type",
  "קבצים שמעלים כאן": "Files uploaded here",
  "נתיב התיקייה בשרת": "Folder path on the server",
  "חיבור לשרת MCP": "MCP server connection",
  "MCP הוא דרך סטנדרטית שבה מערכות (CRM, ויקי, מערכת כרטיסים) חושפות מידע לבינה מלאכותית. מכניסים את הכתובת שהמערכת נותנת.": "MCP is a standard way for systems (CRM, wiki, ticketing) to share data with AI. Enter the address the system gives you.",
  "כתובת השרת": "Server address",
  "מפתח גישה (אם השרת דורש)": "Access token (if the server needs one)",
  "איך להשתמש בו": "How to use it",
  "חיפוש חי: בכל שאלה, לשאול את השרת": "Live search: ask the server on every question",
  "סנכרון: להעתיק את המסמכים שלו לאינדקס": "Sync: copy its documents into the index",
  "כלי החיפוש": "Search tool",
  "השדה שמקבל את השאלה": "Field that takes the question",
  "מי רשאי לחפש במקור הזה": "Who may search this source",

  // reports
  "חודש": "Month",
  "הורדה לאקסל": "Download for Excel",
  "לפי צוות": "By team",
  "תקציב": "Budget",
  "ניצול": "Used",
  "לפי משתמש": "By user",
  "טוקנים": "Tokens",
  "לפי מודל": "By model",
  "מתוכם מהמטמון": "From cache",
  "כל הספקים": "All providers",
  "אנשים ואפליקציות": "People and apps",
  "שהשתמשו בחודש הזה": "Who used it this month",
  "ממוצע לבקשה": "Average per request",
  "עלות ממוצעת": "Average cost",
  "אין שימוש בחודש הזה": "No usage this month",
  // report file (CSV)
  "דוח שימוש בבינה מלאכותית": "AI usage report",
  "הוצאה ($)": "Spend ($)",
  "תקציב ($)": "Budget ($)",
  "טוקנים נכנסים": "Input tokens",
  "טוקנים יוצאים": "Output tokens",
  "טוקנים מהמטמון": "Cached tokens",

  // security
  "סינון לפי סוג אירוע": "Filter by event type",
  "כל האירועים": "All events",
  "בדיקת מצב": "Health check",
  "אירועי אבטחה": "Security events",
  "200 האחרונים": "Last 200",
  "שאלות חשודות נרשמות ולא נחסמות, כי עובדים שואלים בצדק על קוד ופקודות. מסמכים חשודים נחסמים בהעלאה, כי הם מגיעים לכל מי שמחפש בהם. תשובה עם פקודה מסוכנת מקבלת אזהרה לעובד.": "Suspicious questions are logged, not blocked, because employees rightly ask about code and commands. Suspicious documents are blocked on upload, because they reach everyone who searches them. An answer with a dangerous command comes with a warning to the employee.",
  "מתי": "When",
  "אירוע": "Event",
  "פרטים": "Details",
  "שאלה חשודה": "Suspicious question",
  "תשובה עם פקודה מסוכנת": "Answer with a dangerous command",
  "מידע רגיש הוסתר": "Sensitive data masked",
  "בקשה מאתר זר נחסמה": "Cross-site request blocked",
  "כתובת לא מוכרת נחסמה": "Unknown host blocked",
  "חשבון ננעל": "Account locked",
  "סיסמת מנהל שגויה מבחוץ": "Wrong admin password from outside",
  "מסמך חשוד לא נקלט": "Suspicious document refused",
  "מסמך חשוד הועלה באישור": "Suspicious document uploaded with approval",
  "ניסיון לעקוף הוראות": "Attempt to override instructions",
  "קוד דפדפן": "Browser code",
  "פקודה מסוכנת": "Dangerous command",
  "שאלות חשודות": "Suspicious questions",
  "נרשמו ביומן": "Logged",
  "מידע רגיש שהוסתר": "Sensitive data masked",
  "לפני שיצא לספק": "Before it reached the provider",
  "בקשות שנחסמו": "Blocked requests",
  "מאתרים זרים או מבחוץ": "From other sites or outside",
  "תשובות עם פקודה מסוכנת": "Answers with a dangerous command",
  "העובד קיבל אזהרה": "Employee was warned",
  "7 ימים אחרונים": "last 7 days",
  "אין אירועים": "No events",
  // health checks sent by the server
  "חיבור מוצפן (HTTPS) עם דומיין": "Encrypted connection (HTTPS) with a domain",
  "אין דומיין, ולכן החיבור לא מוצפן. השאלות והסיסמאות עוברות ברשת כטקסט גלוי. מתאים לרשת המשרד בלבד.": "No domain, so the connection isn't encrypted. Questions and passwords cross the network as plain text. Fine for the office network only.",
  "מסך הניהול סגור מבחוץ": "The admin screen is closed to outside access",
  "סיסמת המנהל לגישה מבחוץ חזקה": "The admin password for outside access is strong",
  "סיסמת המנהל לגישה מבחוץ קצרה מ-16 תווים": "The admin password for outside access is shorter than 16 characters",
  "לכל מפתחות ה-API יש הגבלת קצב": "Every API key has a rate limit",
  "מפתח API אחד בלי הגבלת קצב. מפתח שדלף יכול לרוקן תקציב מהר.": "One API key has no rate limit. A leaked key can drain a budget fast.",
  "כניסה לצ'אט עם סיסמה": "Chat sign-in needs a password",
  "הצ'אט פתוח בלי סיסמה ברשת המשרד (OPEN_ACCESS): כל אחד יכול לבחור כל שם, להשתמש בתקציב שלו ולראות את השיחות שלו.": "The chat is open without a password on the office network (OPEN_ACCESS): anyone can pick any name, use that person's budget and see their conversations.",
  "אין מפתחות ספקים בקובץ .env": "No provider keys in the .env file",

  // question log
  "סינון לפי שם, צוות או מודל": "Filter by name, team or model",
  "טוקנים נכנסו": "Tokens in",
  "טוקנים יצאו": "Tokens out",
  "עלות": "Cost",
  "מוצגות 200 השאלות האחרונות. כל השאלות נשמרות במסד הנתונים.": "Showing the last 200 questions. All questions are kept in the database.",
  "שאלה ותשובה": "Question and answer",
  "אין שאלות": "No questions",
  "(בדיקת מודל)": "(model test)",
  "(אינדקס מסמכים)": "(document index)",

  // change log
  "פעולה": "Action",
  "אין שינויים עדיין": "No changes yet",
  "חשבון נוצר": "Account created",
  "חשבון עודכן": "Account updated",
  "חשבון נמחק": "Account deleted",
  "הונפק מפתח חדש": "New key issued",
  "מפתח בוטל": "Key revoked",
  "צוות נשמר": "Team saved",
  "צוות נמחק": "Team deleted",
  "מקור מידע נשמר": "Knowledge source saved",
  "מקור מידע נמחק": "Knowledge source deleted",
  "הועלו מסמכים": "Documents uploaded",
  "תיקייה סונכרנה": "Folder synced",
  "מודל נשמר": "Model saved",
  "מודל נמחק": "Model deleted",
  "נקבע מודל ברירת מחדל": "Default model set",
  "בחירה אוטומטית עודכנה": "Automatic choice updated",
  "סיסמה הוחלפה": "Password changed",
  "הודלק": "turned on",
  "כובה": "turned off",
  "נוסף": "added",

  // automatic-choice reasons the server sends (shown next to the answer in the chat)
  "שאלה ארוכה": "long question",
  "קוד, ניתוח או השוואה": "code, analysis or comparison",
  "שיחה ארוכה": "long conversation",
  "שאלה קצרה ופשוטה": "short, simple question",
});

// texts with numbers, money or names inside. Order matters: the " · " splitter first, then specific patterns, generic ones last.
(() => {
  const t = s => (typeof I18N !== "undefined" ? I18N.t(s) : s);
  const M = "(\\$[\\d,.]+)";  // money as admin.js prints it
  const R = s => new RegExp("^" + s.replaceAll("$M", M) + "$");
  const team = (prefix, name) => (prefix ? "team " : "") + name;
  const TIERS = { "מהיר": "fast", "חכם": "smart", "הכי חזק": "strongest", "חסכוני": "lite" };
  window.EN_PATTERNS = (window.EN_PATTERNS || []).concat([
    // model display names ("Claude מהיר") inside any text: swap the name, then translate the rest
    [/^(.*?)(Claude|GPT|Gemini) (מהיר|חכם|הכי חזק|חסכוני)(.*)$/, (_, a, p, k, b) => t(a + p + " " + TIERS[k] + b)],
    // joined texts ("a · b · c"): translate each part on its own
    [/^.+ · .+$/, s => s.split(" · ").map(t).join(" · ")],
    // budgets
    [R("מתוך $M"), "of $1"],
    [R("בחודש שעבר: $M\\. אפשר לעדכן בעריכה\\."), "Last month: $1. You can change it under Edit."],
    [R("אפשר להוריד ל-$M"), "Could go down to $1"],
    [R("בקצב הנוכחי (צוות )?(.+) יוציא $M עד סוף החודש\\."), (_, p, n, m) => `At the current pace, ${team(p, n)} will spend ${m} by the end of the month.`],
    [R("בחודש שעבר (צוות )?(.+) הוציא $M\\. התקציב הנוכחי גבוה בהרבה מהצורך\\."), (_, p, n, m) => `Last month ${team(p, n)} spent ${m}. The current budget is far above what's needed.`],
    [R("לעדכן את התקציב של (צוות )?(.+)\\?"), (_, p, n) => `Update the budget for ${team(p, n)}?`],
    [R("התקציב של (צוות )?(.+) עודכן ל-$M\\."), (_, p, n, m) => `Budget for ${team(p, n)} set to ${m}.`],
    [R("התקציב של (צוות )?(.+) חזר ל-$M\\."), (_, p, n, m) => `Budget for ${team(p, n)} is back to ${m}.`],

    // server errors with details
    [/^שרת ה-MCP: (.*)$/, "MCP server: $1"],
    [/^(.+): לא הצלחנו לקרוא את הקובץ \(פגום או מוצפן\)$/, "$1: couldn't read the file (damaged or encrypted)"],
    [/^(.+): אין בקובץ טקסט \(קובץ סרוק צריך זיהוי טקסט קודם\)$/, "$1: no text in the file (a scanned file needs text recognition first)"],
    [/^(\d+) משתמשים עדיין מורשים להשתמש במודל\. אפשר לכבות אותו, או להסיר אותו מהמשתמשים קודם$/, "$1 users are still allowed to use the model. Turn it off, or remove it from those users first"],
    [/^לא הצלחנו לטעון את הנתונים מהשער \((.*)\)\. ייתכן שהשרת לא זמין\.$/, (_, m) => `Couldn't load data from the gateway (${t(m)}). The server may be down.`],

    // dashboard
    [R("לעומת חודש קודם \\($M\\)"), "vs. last month ($1)"],
    [/^מתוך ([\d,]+) חשבונות$/, "of $1 accounts"],
    [/^(\d+) מתוך (\d+)$/, "$1 of $2"],
    [R("(.+): התקציב האישי נגמר \\($M מתוך $M\\)\\. חסום עד 1 לחודש או עד הגדלת תקציב\\."), "$1: personal budget used up ($2 of $3). Blocked until the 1st of the month or a budget increase."],
    [/^צוות (.+): תקציב הצוות נגמר\. כל חברי הצוות חסומים\.$/, "Team $1: team budget used up. All team members are blocked."],
    [/^צוות (.+): עבר (\d+)% מתקציב הצוות\.$/, "Team $1: passed $2% of the team budget."],
    [/^(.+): עבר (\d+)% מהתקציב האישי\.$/, "$1: passed $2% of the personal budget."],
    [/^(.+): החשבון נעול אחרי 5 סיסמאות שגויות\. איפוס סיסמה משחרר אותו\.$/, "$1: account locked after 5 wrong passwords. Resetting the password unlocks it."],
    [/^(\d+) פריטים$/, "$1 items"],
    [/^(\d+)% מהתקציב$/, "$1% of budget"],
    [R("צפי $M"), "Projected $1"],
    [R("הוצאה מצטברת: $M עד היום, צפי $M לסוף החודש, החודש הקודם $M"), "Cumulative spend: $1 so far, projected $2 by month end, last month $3"],
    [R("תקציבי הצוותים $M"), "Team budgets $1"],
    [R("החודש: $M"), "This month: $1"],
    [R("צפי לסוף החודש: $M"), "Projected by month end: $1"],
    [R("החודש הקודם: $M"), "Last month: $1"],
    [/^(.+): (\d+) משתמשים$/, (_, b, n) => `${t(b)}: ${n} users`],
    [/^עד 50%: .*$/, s => s.replace("עד 50%", "Under 50%").replace("מעל 150%", "Over 150%")],
    [/^יום (\S+), (.+)$/, (_, d, h) => `${t(d)}, ${h}`],
    [R("(אחר|בלי צוות): (.*)"), (_, k, v) => `${t(k)}: ${v}`],
    [/^([\d,]+) בקשות$/, "$1 requests"],

    // users and keys
    [/^(\d+) לדקה$/, "$1/min"],
    [/^עריכת צוות (.+)$/, "Edit team $1"],
    [/^עריכת (.+)$/, "Edit $1"],
    [/^למחוק את צוות (.+)\?$/, "Delete team $1?"],
    [/^למחוק את המקור "(.+)"\?$/, "Delete the source \"$1\"?"],
    [/^למחוק את (.+)\?$/, "Delete $1?"],
    [/^להסיר את (.+)\?$/, "Remove $1?"],
    [/^להנפיק מפתח חדש ל-(.+)\? המפתח הקודם יפסיק לעבוד מיד\.$/, "Issue a new key for $1? The old key stops working right away."],
    [/^לבטל את המפתח של (.+)\? אפליקציות שמשתמשות בו יפסיקו לעבוד מיד\.$/, "Revoke $1's key? Apps that use it stop working right away."],
    [/^השינויים ב-(.+) נשמרו\.$/, "Changes to $1 saved."],
    [/^צוות (.+) נמחק\.$/, "Team $1 deleted."],
    [/^צוות (.+) עודכן\.$/, "Team $1 updated."],
    [/^המקור (.+) נמחק\.$/, "Source $1 deleted."],
    [/^המקור (.+) עודכן\.$/, "Source $1 updated."],
    [/^(.+) נמחק\.$/, "$1 deleted."],
    [/^(.+) נוצר\.$/, "$1 created."],
    [/^(.+) הוסר\.$/, "$1 removed."],
    [/^(.+) עודכן\.$/, "$1 updated."],
    [/^(.+) כובה\.$/, "$1 turned off."],
    [/^(.+) הודלק\.$/, "$1 turned on."],
    [/^(.+) נוסף\. אפשר ללחוץ "בדיקה" כדי לוודא שהוא עובד\.$/, "$1 added. Click \"Test\" to make sure it works."],
    [/^(.+) הוא עכשיו ברירת המחדל\.$/, "$1 is now the default."],
    [/^השאלה והתשובה של (.+), (.+)$/, "$1's question and answer, $2"],

    // change log details
    [R("תקציב $M ← $M"), "Budget $1 → $2"],
    [R("תקציב $M"), "Budget $1"],
    [/^מודלים: (.*)$/, "Models: $1"],
    [/^(\d+) בקשות לדקה$/, "$1 requests per minute"],
    [/^(מחיר נכנס|מחיר יוצא|מחיר מטמון|גיבוי|שם אצל הספק|ספק|פעיל): (.*) ← (.*)$/, (_, k, a, b) =>
      `${{ "מחיר נכנס": "Input price", "מחיר יוצא": "Output price", "מחיר מטמון": "Cache price", "גיבוי": "Backup",
        "שם אצל הספק": "Provider model ID", "ספק": "Provider", "פעיל": "On" }[k]}: ${a} → ${b}`],
    [/^גישה: (.*)$/, (_, v) => `Access: ${v === "אף אחד" ? "no one" : t(v)}`],
    [/^(\d+) קבצים, (\d+) דולגו$/, "$1 files, $2 skipped"],
    [/^(\d+) קבצים$/, "$1 files"],

    // models
    [/^לכבות את (.+)\?$/, "Turn off $1?"],
    [/^(\d+) משתמשים ואפליקציות מורשים להשתמש בו\. מרגע הכיבוי הם יקבלו הודעה שהמודל כבוי, עד שתדליקו אותו שוב\.$/, "$1 users and apps are allowed to use it. Once it's off they get a message that the model is off, until you turn it back on."],
    [/^(\d+) משתמשים עדיין מורשים להשתמש בו, ולכן אי אפשר למחוק\. אפשר לכבות אותו, או להסיר אותו מהמשתמשים קודם\.$/, "$1 users are still allowed to use it, so it can't be deleted. Turn it off, or remove it from those users first."],
    [/^(.+) עונה: החיבור תקין \((\d+) מילישניות\)\.$/, "$1 answers: connection OK ($2 ms)."],
    [/^(.+) לא עונה: אין מפתח של (.+) בקובץ \.env$/, "$1 isn't answering: no $2 key in the .env file"],
    [/^(.+) לא עונה: (.*)$/, "$1 isn't answering: $2"],
    [/^([\d,]+) שאלות נותבו החודש$/, "$1 questions routed this month"],
    [/^(.+) פעיל$/, "$1 on"],
    [/^מחיקת (.+)$/, "Delete $1"],
    [R("חיסכון מהמטמון החודש: $M"), "Cache savings this month: $1"],
    [/^(.+): מחובר$/, "$1: connected"],
    [/^(.+): חסר מפתח$/, "$1: key missing"],
    [/^גיבוי: (.+) לא זמין$/, "backup: $1 unavailable"],
    [/^גיבוי: (.+)$/, "Backup: $1"],
    [/^ענה (\d+) פעמים החודש$/, "answered $1 times this month"],
    [R("חסך $M במטמון"), "Saved $1 via cache"],
    [R("$M לבקשה"), "$1 per request"],
    [/^(חלק מהבקשות|חלק מההוצאה): (\d+)%$/, (_, k, p) => `${t(k)}: ${p}%`],
    [/^(.+): (\d+)% מהבקשות, (\d+)% מההוצאה$/, "$1: $2% of requests, $3% of spend"],
    [/^הוצאה יומית לפי מודל ב-30 הימים האחרונים\. הפירוט המלא בטבלת המודלים שמתחת\.$/, "Daily spend by model over the last 30 days. Full details in the models table below."],
    // automatic-choice reason with a fallback note (server)
    [/^(.+) \(המודל המתאים לא זמין לך\)$/, (_, r) => `${t(r)} (the right model isn't available to you)`],

    // security
    [/^(\d+) ערכים הוסתרו$/, "$1 values masked"],
    [/^קובץ: (.+)$/, "File: $1"],
    [/^כתובת: (.+)$/, "IP: $1"],
    [/^שם שרת: (.+)$/, "Host: $1"],
    [/^אתר מקור: (.+)$/, "Origin: $1"],
    [/^ל-(\d+) דקות$/, "for $1 minutes"],
    [/^(\d+) מפתחות API בלי הגבלת קצב\. מפתח שדלף יכול לרוקן תקציב מהר\.$/, "$1 API keys have no rate limit. A leaked key can drain a budget fast."],
    [/^ספקים מחוברים: (.+)$/, "Connected providers: $1"],

    // knowledge sources
    [/^חיפוש לפי משמעות: פעיל \((.+)\)$/, "Meaning search: on ($1)"],
    [/^([\d,]+) מתוך ([\d,]+) קטעים מאונדקסים\. .*$/, "$1 of $2 passages indexed. A question about \"vacation\" also finds a document that says \"time off\"."],
    [/^לאנדקס ([\d,]+) קטעים$/, "Index $1 passages"],
    [/^([\d.]+[MK]?) תווים$/, "$1 chars"],
    [/^(\d+) מסמכים$/, "$1 documents"],
    [/^(.+): מחובר( ל-(.+))?\.$/, (_, n, __, s) => `${n}: connected${s ? ` to ${s}` : ""}.`],
    [/^(.+): לא מחובר \((.*)\)$/, "$1: not connected ($2)"],
    [/^סונכרנו (\d+) קבצים(.*)$/, (_, n, rest) => `Synced ${n} files` + rest
      .replace(/^\. (\d+) דולגו \(לא טקסט, או גדולים מ-2MB\)/, ". $1 skipped (not text, or larger than 2MB)")
      .replace(/\. (\d+) לא נקלטו בגלל תוכן חשוד: /, ". $1 refused for suspicious content: ")],
    [/^אפשר להעלות קבצים עד 5MB\. גדולים מדי: (.+)$/, "Files up to 5MB can be uploaded. Too big: $1"],
    [/^(.+): (.*)\. מסמך כזה יגיע לכל מי שמחפש במקור\. ההחלטה תירשם ביומן האבטחה\.$/, (_, f, k) =>
      `${f}: ${k.split(", ").map(t).join(", ")}. A document like this reaches everyone who searches the source. The decision is recorded in the security log.`],
    [/^הועלו (\d+) קבצים ל"(.+)"\.$/, "Uploaded $1 files to \"$2\"."],
    [/^לא הצלחנו להתחבר: (.*)$/, "Couldn't connect: $1"],
    [/^מחובר( ל-(.+))?: (\d+) כלים, (\d+) מסמכים\.$/, (_, __, s, n, d) => `Connected${s ? ` to ${s}` : ""}: ${n} tools, ${d} documents.`],

    // generic, kept late so the specific ones above win
    [/^צוות (.+)$/, "Team $1"],
    [/^(.+)\?$/, (_, s) => { const v = t(s); return v === s ? s + "?" : v + "?"; }],
  ]);
})();

// static prose split across inline tags
window.EN_HTML = Object.assign(window.EN_HTML || {}, {
  "#keyDialog p.small": "The key is shown <b>only once</b>. The gateway keeps only an encrypted fingerprint of it, so it can't be recovered. Copy it and hand it over now.",
});
